#ifndef gadtools_cat_H
#define gadtools_cat_H
/*
** gadtools_cat.h Catalog Header File
*/

#include<exec/types.h>

struct FC_Type
{
	LONG ID;
	STRPTR Str;
};

extern const struct FC_Type _MSG_MainProject_MTITLE;
#define MSG_MainProject_MTITLE ((APTR) &_MSG_MainProject_MTITLE)
extern const struct FC_Type _MSG_MainProjectNew_MITEM;
#define MSG_MainProjectNew_MITEM ((APTR) &_MSG_MainProjectNew_MITEM)
extern const struct FC_Type _MSG_MainProjectOpen_MITEM;
#define MSG_MainProjectOpen_MITEM ((APTR) &_MSG_MainProjectOpen_MITEM)
extern const struct FC_Type _MSG_MainProjectSave_MITEM;
#define MSG_MainProjectSave_MITEM ((APTR) &_MSG_MainProjectSave_MITEM)
extern const struct FC_Type _MSG_MainProjectSaveAs_MITEM;
#define MSG_MainProjectSaveAs_MITEM ((APTR) &_MSG_MainProjectSaveAs_MITEM)
extern const struct FC_Type _MSG_MainProjectSaveSource_MITEM;
#define MSG_MainProjectSaveSource_MITEM ((APTR) &_MSG_MainProjectSaveSource_MITEM)
extern const struct FC_Type _MSG_MainProjectPreferences_MITEM;
#define MSG_MainProjectPreferences_MITEM ((APTR) &_MSG_MainProjectPreferences_MITEM)
extern const struct FC_Type _MSG_MainProjectAbout_MITEM;
#define MSG_MainProjectAbout_MITEM ((APTR) &_MSG_MainProjectAbout_MITEM)
extern const struct FC_Type _MSG_MainProjectQuit_MITEM;
#define MSG_MainProjectQuit_MITEM ((APTR) &_MSG_MainProjectQuit_MITEM)
extern const struct FC_Type _MSG_MainEdit_MTITLE;
#define MSG_MainEdit_MTITLE ((APTR) &_MSG_MainEdit_MTITLE)
extern const struct FC_Type _MSG_MainEditUndo_MITEM;
#define MSG_MainEditUndo_MITEM ((APTR) &_MSG_MainEditUndo_MITEM)
extern const struct FC_Type _MSG_MainEditCut_MITEM;
#define MSG_MainEditCut_MITEM ((APTR) &_MSG_MainEditCut_MITEM)
extern const struct FC_Type _MSG_MainEditCopy_MITEM;
#define MSG_MainEditCopy_MITEM ((APTR) &_MSG_MainEditCopy_MITEM)
extern const struct FC_Type _MSG_MainEditPaste_MITEM;
#define MSG_MainEditPaste_MITEM ((APTR) &_MSG_MainEditPaste_MITEM)
extern const struct FC_Type _MSG_MainEditClear_MITEM;
#define MSG_MainEditClear_MITEM ((APTR) &_MSG_MainEditClear_MITEM)
extern const struct FC_Type _MSG_MainEditSelectAll_MITEM;
#define MSG_MainEditSelectAll_MITEM ((APTR) &_MSG_MainEditSelectAll_MITEM)
extern const struct FC_Type _MSG_MainEditGrid_MITEM;
#define MSG_MainEditGrid_MITEM ((APTR) &_MSG_MainEditGrid_MITEM)
extern const struct FC_Type _MSG_MainEditAlign_MITEM;
#define MSG_MainEditAlign_MITEM ((APTR) &_MSG_MainEditAlign_MITEM)
extern const struct FC_Type _MSG_MainEditAlignToLeft_MSUB;
#define MSG_MainEditAlignToLeft_MSUB ((APTR) &_MSG_MainEditAlignToLeft_MSUB)
extern const struct FC_Type _MSG_MainEditAlignToHCenter_MSUB;
#define MSG_MainEditAlignToHCenter_MSUB ((APTR) &_MSG_MainEditAlignToHCenter_MSUB)
extern const struct FC_Type _MSG_MainEditAlignToRight_MSUB;
#define MSG_MainEditAlignToRight_MSUB ((APTR) &_MSG_MainEditAlignToRight_MSUB)
extern const struct FC_Type _MSG_MainEditAlignToTop_MSUB;
#define MSG_MainEditAlignToTop_MSUB ((APTR) &_MSG_MainEditAlignToTop_MSUB)
extern const struct FC_Type _MSG_MainEditAlignToVCenter_MSUB;
#define MSG_MainEditAlignToVCenter_MSUB ((APTR) &_MSG_MainEditAlignToVCenter_MSUB)
extern const struct FC_Type _MSG_MainEditAlignToBottom_MSUB;
#define MSG_MainEditAlignToBottom_MSUB ((APTR) &_MSG_MainEditAlignToBottom_MSUB)
extern const struct FC_Type _MSG_MainEditClone_MITEM;
#define MSG_MainEditClone_MITEM ((APTR) &_MSG_MainEditClone_MITEM)
extern const struct FC_Type _MSG_MainEditCloneWidth_MSUB;
#define MSG_MainEditCloneWidth_MSUB ((APTR) &_MSG_MainEditCloneWidth_MSUB)
extern const struct FC_Type _MSG_MainEditCloneHeight_MSUB;
#define MSG_MainEditCloneHeight_MSUB ((APTR) &_MSG_MainEditCloneHeight_MSUB)
extern const struct FC_Type _MSG_MainEditCloneBoth_MSUB;
#define MSG_MainEditCloneBoth_MSUB ((APTR) &_MSG_MainEditCloneBoth_MSUB)
extern const struct FC_Type _MSG_MainEditSpread_MITEM;
#define MSG_MainEditSpread_MITEM ((APTR) &_MSG_MainEditSpread_MITEM)
extern const struct FC_Type _MSG_MainEditSpreadHoriz_MSUB;
#define MSG_MainEditSpreadHoriz_MSUB ((APTR) &_MSG_MainEditSpreadHoriz_MSUB)
extern const struct FC_Type _MSG_MainEditSpreadVertical_MSUB;
#define MSG_MainEditSpreadVertical_MSUB ((APTR) &_MSG_MainEditSpreadVertical_MSUB)
extern const struct FC_Type _MSG_MainObject_MTITLE;
#define MSG_MainObject_MTITLE ((APTR) &_MSG_MainObject_MTITLE)
extern const struct FC_Type _MSG_MainObjWindow_MITEM;
#define MSG_MainObjWindow_MITEM ((APTR) &_MSG_MainObjWindow_MITEM)
extern const struct FC_Type _MSG_MainObjWindowNew_MSUB;
#define MSG_MainObjWindowNew_MSUB ((APTR) &_MSG_MainObjWindowNew_MSUB)
extern const struct FC_Type _MSG_MainObjWindowClose_MSUB;
#define MSG_MainObjWindowClose_MSUB ((APTR) &_MSG_MainObjWindowClose_MSUB)
extern const struct FC_Type _MSG_MainObjWindowDelete_MSUB;
#define MSG_MainObjWindowDelete_MSUB ((APTR) &_MSG_MainObjWindowDelete_MSUB)
extern const struct FC_Type _MSG_MainObjWindowRefresh_MSUB;
#define MSG_MainObjWindowRefresh_MSUB ((APTR) &_MSG_MainObjWindowRefresh_MSUB)
extern const struct FC_Type _MSG_MainObjMenu_MITEM;
#define MSG_MainObjMenu_MITEM ((APTR) &_MSG_MainObjMenu_MITEM)
extern const struct FC_Type _MSG_MainObjMenuNew_MSUB;
#define MSG_MainObjMenuNew_MSUB ((APTR) &_MSG_MainObjMenuNew_MSUB)
extern const struct FC_Type _MSG_MainObjMenuClose_MSUB;
#define MSG_MainObjMenuClose_MSUB ((APTR) &_MSG_MainObjMenuClose_MSUB)
extern const struct FC_Type _MSG_MainObjMenuDelete_MSUB;
#define MSG_MainObjMenuDelete_MSUB ((APTR) &_MSG_MainObjMenuDelete_MSUB)
extern const struct FC_Type _MSG_MainObjImage_MITEM;
#define MSG_MainObjImage_MITEM ((APTR) &_MSG_MainObjImage_MITEM)
extern const struct FC_Type _MSG_MainObjImageNew_MSUB;
#define MSG_MainObjImageNew_MSUB ((APTR) &_MSG_MainObjImageNew_MSUB)
extern const struct FC_Type _MSG_MainObjImageClose_MSUB;
#define MSG_MainObjImageClose_MSUB ((APTR) &_MSG_MainObjImageClose_MSUB)
extern const struct FC_Type _MSG_MainObjImageDelete_MSUB;
#define MSG_MainObjImageDelete_MSUB ((APTR) &_MSG_MainObjImageDelete_MSUB)
extern const struct FC_Type _MSG_MainObjStrings_MITEM;
#define MSG_MainObjStrings_MITEM ((APTR) &_MSG_MainObjStrings_MITEM)
extern const struct FC_Type _MSG_MainObjStringsOpen_MSUB;
#define MSG_MainObjStringsOpen_MSUB ((APTR) &_MSG_MainObjStringsOpen_MSUB)
extern const struct FC_Type _MSG_MainObjStringsClose_MSUB;
#define MSG_MainObjStringsClose_MSUB ((APTR) &_MSG_MainObjStringsClose_MSUB)
extern const struct FC_Type _MSG_MainObjScreen_MITEM;
#define MSG_MainObjScreen_MITEM ((APTR) &_MSG_MainObjScreen_MITEM)
extern const struct FC_Type _MSG_MainObjScreenOpen_MSUB;
#define MSG_MainObjScreenOpen_MSUB ((APTR) &_MSG_MainObjScreenOpen_MSUB)
extern const struct FC_Type _MSG_MainObjScreenClose_MSUB;
#define MSG_MainObjScreenClose_MSUB ((APTR) &_MSG_MainObjScreenClose_MSUB)
extern const struct FC_Type _MSG_MainObjVersion_MITEM;
#define MSG_MainObjVersion_MITEM ((APTR) &_MSG_MainObjVersion_MITEM)
extern const struct FC_Type _MSG_MainObjVersionOpen_MSUB;
#define MSG_MainObjVersionOpen_MSUB ((APTR) &_MSG_MainObjVersionOpen_MSUB)
extern const struct FC_Type _MSG_MainObjVersionClose_MSUB;
#define MSG_MainObjVersionClose_MSUB ((APTR) &_MSG_MainObjVersionClose_MSUB)
extern const struct FC_Type _MSG_MainWindow_MTITLE;
#define MSG_MainWindow_MTITLE ((APTR) &_MSG_MainWindow_MTITLE)
extern const struct FC_Type _MSG_MainWindowProperties_MITEM;
#define MSG_MainWindowProperties_MITEM ((APTR) &_MSG_MainWindowProperties_MITEM)
extern const struct FC_Type _MSG_MainWindowObjects_MITEM;
#define MSG_MainWindowObjects_MITEM ((APTR) &_MSG_MainWindowObjects_MITEM)
extern const struct FC_Type _MSG_MainWindowStatus_MITEM;
#define MSG_MainWindowStatus_MITEM ((APTR) &_MSG_MainWindowStatus_MITEM)
extern const struct FC_Type _MSG_MainWindowHideAll_MITEM;
#define MSG_MainWindowHideAll_MITEM ((APTR) &_MSG_MainWindowHideAll_MITEM)
extern const struct FC_Type _MSG_SCREENTITLE_SCR;
#define MSG_SCREENTITLE_SCR ((APTR) &_MSG_SCREENTITLE_SCR)
extern const struct FC_Type _MSG_PGBO_LABEL_GAD;
#define MSG_PGBO_LABEL_GAD ((APTR) &_MSG_PGBO_LABEL_GAD)
extern const struct FC_Type _MSG_PGBO_X_GAD;
#define MSG_PGBO_X_GAD ((APTR) &_MSG_PGBO_X_GAD)
extern const struct FC_Type _MSG_PGBO_Y_GAD;
#define MSG_PGBO_Y_GAD ((APTR) &_MSG_PGBO_Y_GAD)
extern const struct FC_Type _MSG_PGBO_WIDTH_GAD;
#define MSG_PGBO_WIDTH_GAD ((APTR) &_MSG_PGBO_WIDTH_GAD)
extern const struct FC_Type _MSG_PGBO_HEIGHT_GAD;
#define MSG_PGBO_HEIGHT_GAD ((APTR) &_MSG_PGBO_HEIGHT_GAD)
extern const struct FC_Type _MSG_PGBO_REL_X_GAD;
#define MSG_PGBO_REL_X_GAD ((APTR) &_MSG_PGBO_REL_X_GAD)
extern const struct FC_Type _MSG_PGBO_REL_X_L0_GAD;
#define MSG_PGBO_REL_X_L0_GAD ((APTR) &_MSG_PGBO_REL_X_L0_GAD)
extern const struct FC_Type _MSG_PGBO_REL_X_L1_GAD;
#define MSG_PGBO_REL_X_L1_GAD ((APTR) &_MSG_PGBO_REL_X_L1_GAD)
extern const struct FC_Type _MSG_PGBO_REL_Y_GAD;
#define MSG_PGBO_REL_Y_GAD ((APTR) &_MSG_PGBO_REL_Y_GAD)
extern const struct FC_Type _MSG_PGBO_REL_Y_L0_GAD;
#define MSG_PGBO_REL_Y_L0_GAD ((APTR) &_MSG_PGBO_REL_Y_L0_GAD)
extern const struct FC_Type _MSG_PGBO_REL_Y_L1_GAD;
#define MSG_PGBO_REL_Y_L1_GAD ((APTR) &_MSG_PGBO_REL_Y_L1_GAD)
extern const struct FC_Type _MSG_PGBO_REL_W_GAD;
#define MSG_PGBO_REL_W_GAD ((APTR) &_MSG_PGBO_REL_W_GAD)
extern const struct FC_Type _MSG_PGBO_REL_W_L0_GAD;
#define MSG_PGBO_REL_W_L0_GAD ((APTR) &_MSG_PGBO_REL_W_L0_GAD)
extern const struct FC_Type _MSG_PGBO_REL_W_L1_GAD;
#define MSG_PGBO_REL_W_L1_GAD ((APTR) &_MSG_PGBO_REL_W_L1_GAD)
extern const struct FC_Type _MSG_PGBO_REL_H_GAD;
#define MSG_PGBO_REL_H_GAD ((APTR) &_MSG_PGBO_REL_H_GAD)
extern const struct FC_Type _MSG_PGBO_REL_H_L0_GAD;
#define MSG_PGBO_REL_H_L0_GAD ((APTR) &_MSG_PGBO_REL_H_L0_GAD)
extern const struct FC_Type _MSG_PGBO_REL_H_L1_GAD;
#define MSG_PGBO_REL_H_L1_GAD ((APTR) &_MSG_PGBO_REL_H_L1_GAD)
extern const struct FC_Type _MSG_ABOUT_OK_GAD;
#define MSG_ABOUT_OK_GAD ((APTR) &_MSG_ABOUT_OK_GAD)
extern const struct FC_Type _MSG_PG_BUTT_FLAGS_IMMEDIATE_GAD;
#define MSG_PG_BUTT_FLAGS_IMMEDIATE_GAD ((APTR) &_MSG_PG_BUTT_FLAGS_IMMEDIATE_GAD)
extern const struct FC_Type _MSG_PG_BUTT_FLAGS_UNDERSCORE_GAD;
#define MSG_PG_BUTT_FLAGS_UNDERSCORE_GAD ((APTR) &_MSG_PG_BUTT_FLAGS_UNDERSCORE_GAD)
extern const struct FC_Type _MSG_PG_BUTT_FLAGS_DISABLED_GAD;
#define MSG_PG_BUTT_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_BUTT_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_BUTT_FLAGS_TITLETYPE_GAD;
#define MSG_PG_BUTT_FLAGS_TITLETYPE_GAD ((APTR) &_MSG_PG_BUTT_FLAGS_TITLETYPE_GAD)
extern const struct FC_Type _MSG_PG_BUTT_FLAGS_TITLETYPE_L0_GAD;
#define MSG_PG_BUTT_FLAGS_TITLETYPE_L0_GAD ((APTR) &_MSG_PG_BUTT_FLAGS_TITLETYPE_L0_GAD)
extern const struct FC_Type _MSG_PG_BUTT_FLAGS_TITLETYPE_L1_GAD;
#define MSG_PG_BUTT_FLAGS_TITLETYPE_L1_GAD ((APTR) &_MSG_PG_BUTT_FLAGS_TITLETYPE_L1_GAD)
extern const struct FC_Type _MSG_PG_BUTT_FLAGS_TITLETYPE_L2_GAD;
#define MSG_PG_BUTT_FLAGS_TITLETYPE_L2_GAD ((APTR) &_MSG_PG_BUTT_FLAGS_TITLETYPE_L2_GAD)
extern const struct FC_Type _MSG_PG_BUTT_FLAGS_TOGGLE_GAD;
#define MSG_PG_BUTT_FLAGS_TOGGLE_GAD ((APTR) &_MSG_PG_BUTT_FLAGS_TOGGLE_GAD)
extern const struct FC_Type _MSG_PG_CBOX_FLAGS_SCALED_GAD;
#define MSG_PG_CBOX_FLAGS_SCALED_GAD ((APTR) &_MSG_PG_CBOX_FLAGS_SCALED_GAD)
extern const struct FC_Type _MSG_PG_CBOX_FLAGS_SCALED_L0_GAD;
#define MSG_PG_CBOX_FLAGS_SCALED_L0_GAD ((APTR) &_MSG_PG_CBOX_FLAGS_SCALED_L0_GAD)
extern const struct FC_Type _MSG_PG_CBOX_FLAGS_SCALED_L1_GAD;
#define MSG_PG_CBOX_FLAGS_SCALED_L1_GAD ((APTR) &_MSG_PG_CBOX_FLAGS_SCALED_L1_GAD)
extern const struct FC_Type _MSG_PG_CBOX_FLAGS_SCALED_L2_GAD;
#define MSG_PG_CBOX_FLAGS_SCALED_L2_GAD ((APTR) &_MSG_PG_CBOX_FLAGS_SCALED_L2_GAD)
extern const struct FC_Type _MSG_PG_CBOX_FLAGS_CHECKED_GAD;
#define MSG_PG_CBOX_FLAGS_CHECKED_GAD ((APTR) &_MSG_PG_CBOX_FLAGS_CHECKED_GAD)
extern const struct FC_Type _MSG_PG_CBOX_FLAGS_HIGHLABEL_GAD;
#define MSG_PG_CBOX_FLAGS_HIGHLABEL_GAD ((APTR) &_MSG_PG_CBOX_FLAGS_HIGHLABEL_GAD)
extern const struct FC_Type _MSG_PG_CBOX_FLAGS_UNDERSCORE_GAD;
#define MSG_PG_CBOX_FLAGS_UNDERSCORE_GAD ((APTR) &_MSG_PG_CBOX_FLAGS_UNDERSCORE_GAD)
extern const struct FC_Type _MSG_PG_CBOX_FLAGS_DISABLED_GAD;
#define MSG_PG_CBOX_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_CBOX_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_CWHL_FLAGS_MAXPENS_GAD;
#define MSG_PG_CWHL_FLAGS_MAXPENS_GAD ((APTR) &_MSG_PG_CWHL_FLAGS_MAXPENS_GAD)
extern const struct FC_Type _MSG_PG_CWHL_FLAGS_ABBRV_GAD;
#define MSG_PG_CWHL_FLAGS_ABBRV_GAD ((APTR) &_MSG_PG_CWHL_FLAGS_ABBRV_GAD)
extern const struct FC_Type _MSG_PG_CWHL_FLAGS_GSLIDER_GAD;
#define MSG_PG_CWHL_FLAGS_GSLIDER_GAD ((APTR) &_MSG_PG_CWHL_FLAGS_GSLIDER_GAD)
extern const struct FC_Type _MSG_PG_CWHL_FLAGS_BEVELBOX_GAD;
#define MSG_PG_CWHL_FLAGS_BEVELBOX_GAD ((APTR) &_MSG_PG_CWHL_FLAGS_BEVELBOX_GAD)
extern const struct FC_Type _MSG_PG_CWHL_FLAGS_DISABLED_GAD;
#define MSG_PG_CWHL_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_CWHL_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_CWHL_FLAGS_FOLLOWMOUSE_GAD;
#define MSG_PG_CWHL_FLAGS_FOLLOWMOUSE_GAD ((APTR) &_MSG_PG_CWHL_FLAGS_FOLLOWMOUSE_GAD)
extern const struct FC_Type _MSG_PG_CYCE_FLAGS_HIGHLABEL_GAD;
#define MSG_PG_CYCE_FLAGS_HIGHLABEL_GAD ((APTR) &_MSG_PG_CYCE_FLAGS_HIGHLABEL_GAD)
extern const struct FC_Type _MSG_PG_CYCE_FLAGS_UNDERSCORE_GAD;
#define MSG_PG_CYCE_FLAGS_UNDERSCORE_GAD ((APTR) &_MSG_PG_CYCE_FLAGS_UNDERSCORE_GAD)
extern const struct FC_Type _MSG_PG_CYCE_FLAGS_DISABLED_GAD;
#define MSG_PG_CYCE_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_CYCE_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_LISTS_EDIT_GAD;
#define MSG_PG_LISTS_EDIT_GAD ((APTR) &_MSG_PG_LISTS_EDIT_GAD)
extern const struct FC_Type _MSG_PG_LISTS_ACTIVE_GAD;
#define MSG_PG_LISTS_ACTIVE_GAD ((APTR) &_MSG_PG_LISTS_ACTIVE_GAD)
extern const struct FC_Type _MSG_PG_LISTS_LIST_GAD;
#define MSG_PG_LISTS_LIST_GAD ((APTR) &_MSG_PG_LISTS_LIST_GAD)
extern const struct FC_Type _MSG_PG_LISTS_UP_GAD;
#define MSG_PG_LISTS_UP_GAD ((APTR) &_MSG_PG_LISTS_UP_GAD)
extern const struct FC_Type _MSG_PG_LISTS_DOWN_GAD;
#define MSG_PG_LISTS_DOWN_GAD ((APTR) &_MSG_PG_LISTS_DOWN_GAD)
extern const struct FC_Type _MSG_PG_LISTS_ADD_GAD;
#define MSG_PG_LISTS_ADD_GAD ((APTR) &_MSG_PG_LISTS_ADD_GAD)
extern const struct FC_Type _MSG_PG_LISTS_DEL_GAD;
#define MSG_PG_LISTS_DEL_GAD ((APTR) &_MSG_PG_LISTS_DEL_GAD)
extern const struct FC_Type _MSG_PG_DTYP_FLAGS_OBJECT_GAD;
#define MSG_PG_DTYP_FLAGS_OBJECT_GAD ((APTR) &_MSG_PG_DTYP_FLAGS_OBJECT_GAD)
extern const struct FC_Type _MSG_PG_DTYP_FLAGS_DISABLED_GAD;
#define MSG_PG_DTYP_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_DTYP_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_GRSL_FLAGS_KNOBPIXELS_GAD;
#define MSG_PG_GRSL_FLAGS_KNOBPIXELS_GAD ((APTR) &_MSG_PG_GRSL_FLAGS_KNOBPIXELS_GAD)
extern const struct FC_Type _MSG_PG_GRSL_FLAGS_MAXVAL_GAD;
#define MSG_PG_GRSL_FLAGS_MAXVAL_GAD ((APTR) &_MSG_PG_GRSL_FLAGS_MAXVAL_GAD)
extern const struct FC_Type _MSG_PG_GRSL_FLAGS_CURVAL_GAD;
#define MSG_PG_GRSL_FLAGS_CURVAL_GAD ((APTR) &_MSG_PG_GRSL_FLAGS_CURVAL_GAD)
extern const struct FC_Type _MSG_PG_GRSL_FLAGS_SKIPVAL_GAD;
#define MSG_PG_GRSL_FLAGS_SKIPVAL_GAD ((APTR) &_MSG_PG_GRSL_FLAGS_SKIPVAL_GAD)
extern const struct FC_Type _MSG_PG_GRSL_FLAGS_PENS_GAD;
#define MSG_PG_GRSL_FLAGS_PENS_GAD ((APTR) &_MSG_PG_GRSL_FLAGS_PENS_GAD)
extern const struct FC_Type _MSG_PG_GRSL_FLAGS_FREEDOM_GAD;
#define MSG_PG_GRSL_FLAGS_FREEDOM_GAD ((APTR) &_MSG_PG_GRSL_FLAGS_FREEDOM_GAD)
extern const struct FC_Type _MSG_PG_GRSL_FLAGS_FREEDOM_L0_GAD;
#define MSG_PG_GRSL_FLAGS_FREEDOM_L0_GAD ((APTR) &_MSG_PG_GRSL_FLAGS_FREEDOM_L0_GAD)
extern const struct FC_Type _MSG_PG_GRSL_FLAGS_FREEDOM_L1_GAD;
#define MSG_PG_GRSL_FLAGS_FREEDOM_L1_GAD ((APTR) &_MSG_PG_GRSL_FLAGS_FREEDOM_L1_GAD)
extern const struct FC_Type _MSG_PG_GRSL_FLAGS_DISABLED_GAD;
#define MSG_PG_GRSL_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_GRSL_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_INTR_FLAGS_DISABLED_GAD;
#define MSG_PG_INTR_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_INTR_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_INTR_FLAGS_UNDERSCORE_GAD;
#define MSG_PG_INTR_FLAGS_UNDERSCORE_GAD ((APTR) &_MSG_PG_INTR_FLAGS_UNDERSCORE_GAD)
extern const struct FC_Type _MSG_PG_INTR_FLAGS_HIGHLABEL_GAD;
#define MSG_PG_INTR_FLAGS_HIGHLABEL_GAD ((APTR) &_MSG_PG_INTR_FLAGS_HIGHLABEL_GAD)
extern const struct FC_Type _MSG_PG_INTR_FLAGS_TABCYCLE_GAD;
#define MSG_PG_INTR_FLAGS_TABCYCLE_GAD ((APTR) &_MSG_PG_INTR_FLAGS_TABCYCLE_GAD)
extern const struct FC_Type _MSG_PG_INTR_FLAGS_REPLACEMODE_GAD;
#define MSG_PG_INTR_FLAGS_REPLACEMODE_GAD ((APTR) &_MSG_PG_INTR_FLAGS_REPLACEMODE_GAD)
extern const struct FC_Type _MSG_PG_INTR_FLAGS_EXITHELP_GAD;
#define MSG_PG_INTR_FLAGS_EXITHELP_GAD ((APTR) &_MSG_PG_INTR_FLAGS_EXITHELP_GAD)
extern const struct FC_Type _MSG_PG_INTR_VAR_MAXCHARS_GAD;
#define MSG_PG_INTR_VAR_MAXCHARS_GAD ((APTR) &_MSG_PG_INTR_VAR_MAXCHARS_GAD)
extern const struct FC_Type _MSG_PG_INTR_VAR_NUMBER_GAD;
#define MSG_PG_INTR_VAR_NUMBER_GAD ((APTR) &_MSG_PG_INTR_VAR_NUMBER_GAD)
extern const struct FC_Type _MSG_PG_INTR_VAR_JUSTIFICATION_GAD;
#define MSG_PG_INTR_VAR_JUSTIFICATION_GAD ((APTR) &_MSG_PG_INTR_VAR_JUSTIFICATION_GAD)
extern const struct FC_Type _MSG_PG_INTR_VAR_JUSTIFICATION_L0_GAD;
#define MSG_PG_INTR_VAR_JUSTIFICATION_L0_GAD ((APTR) &_MSG_PG_INTR_VAR_JUSTIFICATION_L0_GAD)
extern const struct FC_Type _MSG_PG_INTR_VAR_JUSTIFICATION_L1_GAD;
#define MSG_PG_INTR_VAR_JUSTIFICATION_L1_GAD ((APTR) &_MSG_PG_INTR_VAR_JUSTIFICATION_L1_GAD)
extern const struct FC_Type _MSG_PG_INTR_VAR_JUSTIFICATION_L2_GAD;
#define MSG_PG_INTR_VAR_JUSTIFICATION_L2_GAD ((APTR) &_MSG_PG_INTR_VAR_JUSTIFICATION_L2_GAD)
extern const struct FC_Type _MSG_PG_LVIE_FLAGS_ARROWS_GAD;
#define MSG_PG_LVIE_FLAGS_ARROWS_GAD ((APTR) &_MSG_PG_LVIE_FLAGS_ARROWS_GAD)
extern const struct FC_Type _MSG_PG_LVIE_FLAGS_SPACING_GAD;
#define MSG_PG_LVIE_FLAGS_SPACING_GAD ((APTR) &_MSG_PG_LVIE_FLAGS_SPACING_GAD)
extern const struct FC_Type _MSG_PG_LVIE_FLAGS_DISABLED_GAD;
#define MSG_PG_LVIE_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_LVIE_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_LVIE_FLAGS_UNDERSCORE_GAD;
#define MSG_PG_LVIE_FLAGS_UNDERSCORE_GAD ((APTR) &_MSG_PG_LVIE_FLAGS_UNDERSCORE_GAD)
extern const struct FC_Type _MSG_PG_LVIE_FLAGS_HIGHLABEL_GAD;
#define MSG_PG_LVIE_FLAGS_HIGHLABEL_GAD ((APTR) &_MSG_PG_LVIE_FLAGS_HIGHLABEL_GAD)
extern const struct FC_Type _MSG_PG_LVIE_FLAGS_READONLY_GAD;
#define MSG_PG_LVIE_FLAGS_READONLY_GAD ((APTR) &_MSG_PG_LVIE_FLAGS_READONLY_GAD)
extern const struct FC_Type _MSG_PG_LVIE_FLAGS_SHOWSELECTED_GAD;
#define MSG_PG_LVIE_FLAGS_SHOWSELECTED_GAD ((APTR) &_MSG_PG_LVIE_FLAGS_SHOWSELECTED_GAD)
extern const struct FC_Type _MSG_PG_LVIE_FLAGS_ARROWS_SEL_GAD;
#define MSG_PG_LVIE_FLAGS_ARROWS_SEL_GAD ((APTR) &_MSG_PG_LVIE_FLAGS_ARROWS_SEL_GAD)
extern const struct FC_Type _MSG_PG_LVIE_FLAGS_ARROWS_SEL_L0_GAD;
#define MSG_PG_LVIE_FLAGS_ARROWS_SEL_L0_GAD ((APTR) &_MSG_PG_LVIE_FLAGS_ARROWS_SEL_L0_GAD)
extern const struct FC_Type _MSG_PG_LVIE_FLAGS_ARROWS_SEL_L1_GAD;
#define MSG_PG_LVIE_FLAGS_ARROWS_SEL_L1_GAD ((APTR) &_MSG_PG_LVIE_FLAGS_ARROWS_SEL_L1_GAD)
extern const struct FC_Type _MSG_PG_LVIE_FLAGS_ARROWS_SEL_L2_GAD;
#define MSG_PG_LVIE_FLAGS_ARROWS_SEL_L2_GAD ((APTR) &_MSG_PG_LVIE_FLAGS_ARROWS_SEL_L2_GAD)
extern const struct FC_Type _MSG_PG_MX_FLAGS_DISABLED_GAD;
#define MSG_PG_MX_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_MX_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_MX_FLAGS_UNDERSCORE_GAD;
#define MSG_PG_MX_FLAGS_UNDERSCORE_GAD ((APTR) &_MSG_PG_MX_FLAGS_UNDERSCORE_GAD)
extern const struct FC_Type _MSG_PG_MX_FLAGS_HIGHLABEL_GAD;
#define MSG_PG_MX_FLAGS_HIGHLABEL_GAD ((APTR) &_MSG_PG_MX_FLAGS_HIGHLABEL_GAD)
extern const struct FC_Type _MSG_PG_MX_FLAGS_SCALED_GAD;
#define MSG_PG_MX_FLAGS_SCALED_GAD ((APTR) &_MSG_PG_MX_FLAGS_SCALED_GAD)
extern const struct FC_Type _MSG_PG_MX_FLAGS_SCALED_L0_GAD;
#define MSG_PG_MX_FLAGS_SCALED_L0_GAD ((APTR) &_MSG_PG_MX_FLAGS_SCALED_L0_GAD)
extern const struct FC_Type _MSG_PG_MX_FLAGS_SCALED_L1_GAD;
#define MSG_PG_MX_FLAGS_SCALED_L1_GAD ((APTR) &_MSG_PG_MX_FLAGS_SCALED_L1_GAD)
extern const struct FC_Type _MSG_PG_MX_FLAGS_SCALED_L2_GAD;
#define MSG_PG_MX_FLAGS_SCALED_L2_GAD ((APTR) &_MSG_PG_MX_FLAGS_SCALED_L2_GAD)
extern const struct FC_Type _MSG_PG_MX_FLAGS_PLACEMENT_GAD;
#define MSG_PG_MX_FLAGS_PLACEMENT_GAD ((APTR) &_MSG_PG_MX_FLAGS_PLACEMENT_GAD)
extern const struct FC_Type _MSG_PG_MX_FLAGS_PLACEMENT_L0_GAD;
#define MSG_PG_MX_FLAGS_PLACEMENT_L0_GAD ((APTR) &_MSG_PG_MX_FLAGS_PLACEMENT_L0_GAD)
extern const struct FC_Type _MSG_PG_MX_FLAGS_PLACEMENT_L1_GAD;
#define MSG_PG_MX_FLAGS_PLACEMENT_L1_GAD ((APTR) &_MSG_PG_MX_FLAGS_PLACEMENT_L1_GAD)
extern const struct FC_Type _MSG_PG_MX_FLAGS_PLACEMENT_L2_GAD;
#define MSG_PG_MX_FLAGS_PLACEMENT_L2_GAD ((APTR) &_MSG_PG_MX_FLAGS_PLACEMENT_L2_GAD)
extern const struct FC_Type _MSG_PG_MX_FLAGS_PLACEMENT_L3_GAD;
#define MSG_PG_MX_FLAGS_PLACEMENT_L3_GAD ((APTR) &_MSG_PG_MX_FLAGS_PLACEMENT_L3_GAD)
extern const struct FC_Type _MSG_PG_MX_FLAGS_SPACING_GAD;
#define MSG_PG_MX_FLAGS_SPACING_GAD ((APTR) &_MSG_PG_MX_FLAGS_SPACING_GAD)
extern const struct FC_Type _MSG_PG_NUMB_FLAGS_FORMAT_GAD;
#define MSG_PG_NUMB_FLAGS_FORMAT_GAD ((APTR) &_MSG_PG_NUMB_FLAGS_FORMAT_GAD)
extern const struct FC_Type _MSG_PG_NUMB_FLAGS_DEFAULT_GAD;
#define MSG_PG_NUMB_FLAGS_DEFAULT_GAD ((APTR) &_MSG_PG_NUMB_FLAGS_DEFAULT_GAD)
extern const struct FC_Type _MSG_PG_NUMB_FLAGS_MAXNUMLEN_GAD;
#define MSG_PG_NUMB_FLAGS_MAXNUMLEN_GAD ((APTR) &_MSG_PG_NUMB_FLAGS_MAXNUMLEN_GAD)
extern const struct FC_Type _MSG_PG_NUMB_FLAGS_DISABLED_GAD;
#define MSG_PG_NUMB_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_NUMB_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_NUMB_FLAGS_HIGHLABEL_GAD;
#define MSG_PG_NUMB_FLAGS_HIGHLABEL_GAD ((APTR) &_MSG_PG_NUMB_FLAGS_HIGHLABEL_GAD)
extern const struct FC_Type _MSG_PG_NUMB_FLAGS_BORDER_GAD;
#define MSG_PG_NUMB_FLAGS_BORDER_GAD ((APTR) &_MSG_PG_NUMB_FLAGS_BORDER_GAD)
extern const struct FC_Type _MSG_PG_NUMB_FLAGS_CLIPPED_GAD;
#define MSG_PG_NUMB_FLAGS_CLIPPED_GAD ((APTR) &_MSG_PG_NUMB_FLAGS_CLIPPED_GAD)
extern const struct FC_Type _MSG_PG_NUMB_FLAGS_JUSTIFICATION_GAD;
#define MSG_PG_NUMB_FLAGS_JUSTIFICATION_GAD ((APTR) &_MSG_PG_NUMB_FLAGS_JUSTIFICATION_GAD)
extern const struct FC_Type _MSG_PG_NUMB_FLAGS_JUSTIFICATION_L0_GAD;
#define MSG_PG_NUMB_FLAGS_JUSTIFICATION_L0_GAD ((APTR) &_MSG_PG_NUMB_FLAGS_JUSTIFICATION_L0_GAD)
extern const struct FC_Type _MSG_PG_NUMB_FLAGS_JUSTIFICATION_L1_GAD;
#define MSG_PG_NUMB_FLAGS_JUSTIFICATION_L1_GAD ((APTR) &_MSG_PG_NUMB_FLAGS_JUSTIFICATION_L1_GAD)
extern const struct FC_Type _MSG_PG_NUMB_FLAGS_JUSTIFICATION_L2_GAD;
#define MSG_PG_NUMB_FLAGS_JUSTIFICATION_L2_GAD ((APTR) &_MSG_PG_NUMB_FLAGS_JUSTIFICATION_L2_GAD)
extern const struct FC_Type _MSG_PGGT_LABEL_GAD;
#define MSG_PGGT_LABEL_GAD ((APTR) &_MSG_PGGT_LABEL_GAD)
extern const struct FC_Type _MSG_PGGT_TITLE_GAD;
#define MSG_PGGT_TITLE_GAD ((APTR) &_MSG_PGGT_TITLE_GAD)
extern const struct FC_Type _MSG_PGGT_X_GAD;
#define MSG_PGGT_X_GAD ((APTR) &_MSG_PGGT_X_GAD)
extern const struct FC_Type _MSG_PGGT_Y_GAD;
#define MSG_PGGT_Y_GAD ((APTR) &_MSG_PGGT_Y_GAD)
extern const struct FC_Type _MSG_PGGT_WIDTH_GAD;
#define MSG_PGGT_WIDTH_GAD ((APTR) &_MSG_PGGT_WIDTH_GAD)
extern const struct FC_Type _MSG_PGGT_HEIGHT_GAD;
#define MSG_PGGT_HEIGHT_GAD ((APTR) &_MSG_PGGT_HEIGHT_GAD)
extern const struct FC_Type _MSG_PGGT_PLACEMENT_GAD;
#define MSG_PGGT_PLACEMENT_GAD ((APTR) &_MSG_PGGT_PLACEMENT_GAD)
extern const struct FC_Type _MSG_PGGT_PLACEMENT_L0_GAD;
#define MSG_PGGT_PLACEMENT_L0_GAD ((APTR) &_MSG_PGGT_PLACEMENT_L0_GAD)
extern const struct FC_Type _MSG_PGGT_PLACEMENT_L1_GAD;
#define MSG_PGGT_PLACEMENT_L1_GAD ((APTR) &_MSG_PGGT_PLACEMENT_L1_GAD)
extern const struct FC_Type _MSG_PGGT_PLACEMENT_L2_GAD;
#define MSG_PGGT_PLACEMENT_L2_GAD ((APTR) &_MSG_PGGT_PLACEMENT_L2_GAD)
extern const struct FC_Type _MSG_PGGT_PLACEMENT_L3_GAD;
#define MSG_PGGT_PLACEMENT_L3_GAD ((APTR) &_MSG_PGGT_PLACEMENT_L3_GAD)
extern const struct FC_Type _MSG_PGGT_PLACEMENT_L4_GAD;
#define MSG_PGGT_PLACEMENT_L4_GAD ((APTR) &_MSG_PGGT_PLACEMENT_L4_GAD)
extern const struct FC_Type _MSG_PGGT_REL_X_GAD;
#define MSG_PGGT_REL_X_GAD ((APTR) &_MSG_PGGT_REL_X_GAD)
extern const struct FC_Type _MSG_PGGT_REL_X_L0_GAD;
#define MSG_PGGT_REL_X_L0_GAD ((APTR) &_MSG_PGGT_REL_X_L0_GAD)
extern const struct FC_Type _MSG_PGGT_REL_X_L1_GAD;
#define MSG_PGGT_REL_X_L1_GAD ((APTR) &_MSG_PGGT_REL_X_L1_GAD)
extern const struct FC_Type _MSG_PGGT_REL_Y_GAD;
#define MSG_PGGT_REL_Y_GAD ((APTR) &_MSG_PGGT_REL_Y_GAD)
extern const struct FC_Type _MSG_PGGT_REL_Y_L0_GAD;
#define MSG_PGGT_REL_Y_L0_GAD ((APTR) &_MSG_PGGT_REL_Y_L0_GAD)
extern const struct FC_Type _MSG_PGGT_REL_Y_L1_GAD;
#define MSG_PGGT_REL_Y_L1_GAD ((APTR) &_MSG_PGGT_REL_Y_L1_GAD)
extern const struct FC_Type _MSG_PGGT_REL_W_GAD;
#define MSG_PGGT_REL_W_GAD ((APTR) &_MSG_PGGT_REL_W_GAD)
extern const struct FC_Type _MSG_PGGT_REL_W_L0_GAD;
#define MSG_PGGT_REL_W_L0_GAD ((APTR) &_MSG_PGGT_REL_W_L0_GAD)
extern const struct FC_Type _MSG_PGGT_REL_W_L1_GAD;
#define MSG_PGGT_REL_W_L1_GAD ((APTR) &_MSG_PGGT_REL_W_L1_GAD)
extern const struct FC_Type _MSG_PGGT_REL_H_GAD;
#define MSG_PGGT_REL_H_GAD ((APTR) &_MSG_PGGT_REL_H_GAD)
extern const struct FC_Type _MSG_PGGT_REL_H_L0_GAD;
#define MSG_PGGT_REL_H_L0_GAD ((APTR) &_MSG_PGGT_REL_H_L0_GAD)
extern const struct FC_Type _MSG_PGGT_REL_H_L1_GAD;
#define MSG_PGGT_REL_H_L1_GAD ((APTR) &_MSG_PGGT_REL_H_L1_GAD)
extern const struct FC_Type _MSG_PG_PAGE_FLAGS_DISABLED_GAD;
#define MSG_PG_PAGE_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_PAGE_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_PAGE_FLAGS_UNDERSCORE_GAD;
#define MSG_PG_PAGE_FLAGS_UNDERSCORE_GAD ((APTR) &_MSG_PG_PAGE_FLAGS_UNDERSCORE_GAD)
extern const struct FC_Type _MSG_PG_PAGE_FLAGS_LAYOUT_GAD;
#define MSG_PG_PAGE_FLAGS_LAYOUT_GAD ((APTR) &_MSG_PG_PAGE_FLAGS_LAYOUT_GAD)
extern const struct FC_Type _MSG_PG_PAGE_FLAGS_LAYOUT_L0_GAD;
#define MSG_PG_PAGE_FLAGS_LAYOUT_L0_GAD ((APTR) &_MSG_PG_PAGE_FLAGS_LAYOUT_L0_GAD)
extern const struct FC_Type _MSG_PG_PAGE_FLAGS_LAYOUT_L1_GAD;
#define MSG_PG_PAGE_FLAGS_LAYOUT_L1_GAD ((APTR) &_MSG_PG_PAGE_FLAGS_LAYOUT_L1_GAD)
extern const struct FC_Type _MSG_PG_PAGE_FLAGS_LAYOUT_L2_GAD;
#define MSG_PG_PAGE_FLAGS_LAYOUT_L2_GAD ((APTR) &_MSG_PG_PAGE_FLAGS_LAYOUT_L2_GAD)
extern const struct FC_Type _MSG_PG_PAGE_FLAGS_STYLE_GAD;
#define MSG_PG_PAGE_FLAGS_STYLE_GAD ((APTR) &_MSG_PG_PAGE_FLAGS_STYLE_GAD)
extern const struct FC_Type _MSG_PG_PAGE_FLAGS_STYLE_L0_GAD;
#define MSG_PG_PAGE_FLAGS_STYLE_L0_GAD ((APTR) &_MSG_PG_PAGE_FLAGS_STYLE_L0_GAD)
extern const struct FC_Type _MSG_PG_PAGE_FLAGS_STYLE_L1_GAD;
#define MSG_PG_PAGE_FLAGS_STYLE_L1_GAD ((APTR) &_MSG_PG_PAGE_FLAGS_STYLE_L1_GAD)
extern const struct FC_Type _MSG_PG_PAGE_FLAGS_STYLE_L2_GAD;
#define MSG_PG_PAGE_FLAGS_STYLE_L2_GAD ((APTR) &_MSG_PG_PAGE_FLAGS_STYLE_L2_GAD)
extern const struct FC_Type _MSG_PG_PAGE_LISTS_LIST_GAD;
#define MSG_PG_PAGE_LISTS_LIST_GAD ((APTR) &_MSG_PG_PAGE_LISTS_LIST_GAD)
extern const struct FC_Type _MSG_PG_PAGE_LISTS_ADD_GAD;
#define MSG_PG_PAGE_LISTS_ADD_GAD ((APTR) &_MSG_PG_PAGE_LISTS_ADD_GAD)
extern const struct FC_Type _MSG_PG_PAGE_LISTS_DEL_GAD;
#define MSG_PG_PAGE_LISTS_DEL_GAD ((APTR) &_MSG_PG_PAGE_LISTS_DEL_GAD)
extern const struct FC_Type _MSG_PG_PAGE_LISTS_UP_GAD;
#define MSG_PG_PAGE_LISTS_UP_GAD ((APTR) &_MSG_PG_PAGE_LISTS_UP_GAD)
extern const struct FC_Type _MSG_PG_PAGE_LISTS_DOWN_GAD;
#define MSG_PG_PAGE_LISTS_DOWN_GAD ((APTR) &_MSG_PG_PAGE_LISTS_DOWN_GAD)
extern const struct FC_Type _MSG_PG_PAGE_LISTS_WINDOWS_GAD;
#define MSG_PG_PAGE_LISTS_WINDOWS_GAD ((APTR) &_MSG_PG_PAGE_LISTS_WINDOWS_GAD)
extern const struct FC_Type _MSG_PG_PAGE_LISTS_ACTIVE_GAD;
#define MSG_PG_PAGE_LISTS_ACTIVE_GAD ((APTR) &_MSG_PG_PAGE_LISTS_ACTIVE_GAD)
extern const struct FC_Type _MSG_PG_PALT_FLAGS_COLOR_GAD;
#define MSG_PG_PALT_FLAGS_COLOR_GAD ((APTR) &_MSG_PG_PALT_FLAGS_COLOR_GAD)
extern const struct FC_Type _MSG_PG_PALT_FLAGS_OFFSET_GAD;
#define MSG_PG_PALT_FLAGS_OFFSET_GAD ((APTR) &_MSG_PG_PALT_FLAGS_OFFSET_GAD)
extern const struct FC_Type _MSG_PG_PALT_FLAGS_SHOWSELECTED_VAR_GAD;
#define MSG_PG_PALT_FLAGS_SHOWSELECTED_VAR_GAD ((APTR) &_MSG_PG_PALT_FLAGS_SHOWSELECTED_VAR_GAD)
extern const struct FC_Type _MSG_PG_PALT_FLAGS_SHOWSELECTED_GAD;
#define MSG_PG_PALT_FLAGS_SHOWSELECTED_GAD ((APTR) &_MSG_PG_PALT_FLAGS_SHOWSELECTED_GAD)
extern const struct FC_Type _MSG_PG_PALT_FLAGS_SHOWSELECTED_L0_GAD;
#define MSG_PG_PALT_FLAGS_SHOWSELECTED_L0_GAD ((APTR) &_MSG_PG_PALT_FLAGS_SHOWSELECTED_L0_GAD)
extern const struct FC_Type _MSG_PG_PALT_FLAGS_SHOWSELECTED_L1_GAD;
#define MSG_PG_PALT_FLAGS_SHOWSELECTED_L1_GAD ((APTR) &_MSG_PG_PALT_FLAGS_SHOWSELECTED_L1_GAD)
extern const struct FC_Type _MSG_PG_PALT_FLAGS_SHOWSELECTED_L2_GAD;
#define MSG_PG_PALT_FLAGS_SHOWSELECTED_L2_GAD ((APTR) &_MSG_PG_PALT_FLAGS_SHOWSELECTED_L2_GAD)
extern const struct FC_Type _MSG_PG_PALT_FLAGS_DISABLED_GAD;
#define MSG_PG_PALT_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_PALT_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_PALT_FLAGS_UNDERSCORE_GAD;
#define MSG_PG_PALT_FLAGS_UNDERSCORE_GAD ((APTR) &_MSG_PG_PALT_FLAGS_UNDERSCORE_GAD)
extern const struct FC_Type _MSG_PG_PALT_FLAGS_HIGHLABEL_GAD;
#define MSG_PG_PALT_FLAGS_HIGHLABEL_GAD ((APTR) &_MSG_PG_PALT_FLAGS_HIGHLABEL_GAD)
extern const struct FC_Type _MSG_PG_PALT_FLAGS_TYPE_GAD;
#define MSG_PG_PALT_FLAGS_TYPE_GAD ((APTR) &_MSG_PG_PALT_FLAGS_TYPE_GAD)
extern const struct FC_Type _MSG_PG_PALT_FLAGS_TYPE_L0_GAD;
#define MSG_PG_PALT_FLAGS_TYPE_L0_GAD ((APTR) &_MSG_PG_PALT_FLAGS_TYPE_L0_GAD)
extern const struct FC_Type _MSG_PG_PALT_FLAGS_TYPE_L1_GAD;
#define MSG_PG_PALT_FLAGS_TYPE_L1_GAD ((APTR) &_MSG_PG_PALT_FLAGS_TYPE_L1_GAD)
extern const struct FC_Type _MSG_PG_PALT_FLAGS_TYPE_L2_GAD;
#define MSG_PG_PALT_FLAGS_TYPE_L2_GAD ((APTR) &_MSG_PG_PALT_FLAGS_TYPE_L2_GAD)
extern const struct FC_Type _MSG_PG_PUPM_FLAGS_DISABLED_GAD;
#define MSG_PG_PUPM_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_PUPM_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_PUPM_FLAGS_NEWLOOK_GAD;
#define MSG_PG_PUPM_FLAGS_NEWLOOK_GAD ((APTR) &_MSG_PG_PUPM_FLAGS_NEWLOOK_GAD)
extern const struct FC_Type _MSG_PG_PRGR_FLAGS_MAX_GAD;
#define MSG_PG_PRGR_FLAGS_MAX_GAD ((APTR) &_MSG_PG_PRGR_FLAGS_MAX_GAD)
extern const struct FC_Type _MSG_PG_PRGR_FLAGS_CURRENT_GAD;
#define MSG_PG_PRGR_FLAGS_CURRENT_GAD ((APTR) &_MSG_PG_PRGR_FLAGS_CURRENT_GAD)
extern const struct FC_Type _MSG_PG_PRGR_FLAGS_FORMAT_GAD;
#define MSG_PG_PRGR_FLAGS_FORMAT_GAD ((APTR) &_MSG_PG_PRGR_FLAGS_FORMAT_GAD)
extern const struct FC_Type _MSG_PG_PRGR_FLAGS_DISABLED_GAD;
#define MSG_PG_PRGR_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_PRGR_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_PRGR_FLAGS_BORDER_GAD;
#define MSG_PG_PRGR_FLAGS_BORDER_GAD ((APTR) &_MSG_PG_PRGR_FLAGS_BORDER_GAD)
extern const struct FC_Type _MSG_PG_PRGR_FLAGS_PERCENTS_GAD;
#define MSG_PG_PRGR_FLAGS_PERCENTS_GAD ((APTR) &_MSG_PG_PRGR_FLAGS_PERCENTS_GAD)
extern const struct FC_Type _MSG_PG_PRGR_FLAGS_PLACEMENT_GAD;
#define MSG_PG_PRGR_FLAGS_PLACEMENT_GAD ((APTR) &_MSG_PG_PRGR_FLAGS_PLACEMENT_GAD)
extern const struct FC_Type _MSG_PG_PRGR_FLAGS_PLACEMENT_L0_GAD;
#define MSG_PG_PRGR_FLAGS_PLACEMENT_L0_GAD ((APTR) &_MSG_PG_PRGR_FLAGS_PLACEMENT_L0_GAD)
extern const struct FC_Type _MSG_PG_PRGR_FLAGS_PLACEMENT_L1_GAD;
#define MSG_PG_PRGR_FLAGS_PLACEMENT_L1_GAD ((APTR) &_MSG_PG_PRGR_FLAGS_PLACEMENT_L1_GAD)
extern const struct FC_Type _MSG_PG_PRGR_FLAGS_PLACEMENT_L2_GAD;
#define MSG_PG_PRGR_FLAGS_PLACEMENT_L2_GAD ((APTR) &_MSG_PG_PRGR_FLAGS_PLACEMENT_L2_GAD)
extern const struct FC_Type _MSG_PG_PRGR_FLAGS_PLACEMENT_L3_GAD;
#define MSG_PG_PRGR_FLAGS_PLACEMENT_L3_GAD ((APTR) &_MSG_PG_PRGR_FLAGS_PLACEMENT_L3_GAD)
extern const struct FC_Type _MSG_PG_PRGR_FLAGS_PLACEMENT_L4_GAD;
#define MSG_PG_PRGR_FLAGS_PLACEMENT_L4_GAD ((APTR) &_MSG_PG_PRGR_FLAGS_PLACEMENT_L4_GAD)
extern const struct FC_Type _MSG_PG_SCRL_FLAGS_DISABLED_GAD;
#define MSG_PG_SCRL_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_SCRL_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_SCRL_FLAGS_UNDERSCORE_GAD;
#define MSG_PG_SCRL_FLAGS_UNDERSCORE_GAD ((APTR) &_MSG_PG_SCRL_FLAGS_UNDERSCORE_GAD)
extern const struct FC_Type _MSG_PG_SCRL_FLAGS_HIGHLABEL_GAD;
#define MSG_PG_SCRL_FLAGS_HIGHLABEL_GAD ((APTR) &_MSG_PG_SCRL_FLAGS_HIGHLABEL_GAD)
extern const struct FC_Type _MSG_PG_SCRL_FLAGS_IMMEDIATE_GAD;
#define MSG_PG_SCRL_FLAGS_IMMEDIATE_GAD ((APTR) &_MSG_PG_SCRL_FLAGS_IMMEDIATE_GAD)
extern const struct FC_Type _MSG_PG_SCRL_FLAGS_RELVERIFY_GAD;
#define MSG_PG_SCRL_FLAGS_RELVERIFY_GAD ((APTR) &_MSG_PG_SCRL_FLAGS_RELVERIFY_GAD)
extern const struct FC_Type _MSG_PG_SCRL_VAR_TOP_GAD;
#define MSG_PG_SCRL_VAR_TOP_GAD ((APTR) &_MSG_PG_SCRL_VAR_TOP_GAD)
extern const struct FC_Type _MSG_PG_SCRL_VAR_TOTAL_GAD;
#define MSG_PG_SCRL_VAR_TOTAL_GAD ((APTR) &_MSG_PG_SCRL_VAR_TOTAL_GAD)
extern const struct FC_Type _MSG_PG_SCRL_VAR_VISIBLE_GAD;
#define MSG_PG_SCRL_VAR_VISIBLE_GAD ((APTR) &_MSG_PG_SCRL_VAR_VISIBLE_GAD)
extern const struct FC_Type _MSG_PG_SCRL_VAR_FREEDOM_GAD;
#define MSG_PG_SCRL_VAR_FREEDOM_GAD ((APTR) &_MSG_PG_SCRL_VAR_FREEDOM_GAD)
extern const struct FC_Type _MSG_PG_SCRL_VAR_FREEDOM_L0_GAD;
#define MSG_PG_SCRL_VAR_FREEDOM_L0_GAD ((APTR) &_MSG_PG_SCRL_VAR_FREEDOM_L0_GAD)
extern const struct FC_Type _MSG_PG_SCRL_VAR_FREEDOM_L1_GAD;
#define MSG_PG_SCRL_VAR_FREEDOM_L1_GAD ((APTR) &_MSG_PG_SCRL_VAR_FREEDOM_L1_GAD)
extern const struct FC_Type _MSG_PG_SCRL_VAR_ARROWS_GAD;
#define MSG_PG_SCRL_VAR_ARROWS_GAD ((APTR) &_MSG_PG_SCRL_VAR_ARROWS_GAD)
extern const struct FC_Type _MSG_PG_SCRL_VAR_ARROW_TYPE_GAD;
#define MSG_PG_SCRL_VAR_ARROW_TYPE_GAD ((APTR) &_MSG_PG_SCRL_VAR_ARROW_TYPE_GAD)
extern const struct FC_Type _MSG_PG_SCRL_VAR_ARROW_TYPE_L0_GAD;
#define MSG_PG_SCRL_VAR_ARROW_TYPE_L0_GAD ((APTR) &_MSG_PG_SCRL_VAR_ARROW_TYPE_L0_GAD)
extern const struct FC_Type _MSG_PG_SCRL_VAR_ARROW_TYPE_L1_GAD;
#define MSG_PG_SCRL_VAR_ARROW_TYPE_L1_GAD ((APTR) &_MSG_PG_SCRL_VAR_ARROW_TYPE_L1_GAD)
extern const struct FC_Type _MSG_PG_SCRL_VAR_ARROW_TYPE_L2_GAD;
#define MSG_PG_SCRL_VAR_ARROW_TYPE_L2_GAD ((APTR) &_MSG_PG_SCRL_VAR_ARROW_TYPE_L2_GAD)
extern const struct FC_Type _MSG_PG_SLIR_FLAGS_FORMAT_GAD;
#define MSG_PG_SLIR_FLAGS_FORMAT_GAD ((APTR) &_MSG_PG_SLIR_FLAGS_FORMAT_GAD)
extern const struct FC_Type _MSG_PG_SLIR_FLAGS_MAXPIXELLEN_GAD;
#define MSG_PG_SLIR_FLAGS_MAXPIXELLEN_GAD ((APTR) &_MSG_PG_SLIR_FLAGS_MAXPIXELLEN_GAD)
extern const struct FC_Type _MSG_PG_SLIR_FLAGS_MAXPIXELLEN_SET_GAD;
#define MSG_PG_SLIR_FLAGS_MAXPIXELLEN_SET_GAD ((APTR) &_MSG_PG_SLIR_FLAGS_MAXPIXELLEN_SET_GAD)
extern const struct FC_Type _MSG_PG_SLIR_FLAGS_DISABLED_GAD;
#define MSG_PG_SLIR_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_SLIR_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_SLIR_FLAGS_UNDERSCORE_GAD;
#define MSG_PG_SLIR_FLAGS_UNDERSCORE_GAD ((APTR) &_MSG_PG_SLIR_FLAGS_UNDERSCORE_GAD)
extern const struct FC_Type _MSG_PG_SLIR_FLAGS_HIGHLABEL_GAD;
#define MSG_PG_SLIR_FLAGS_HIGHLABEL_GAD ((APTR) &_MSG_PG_SLIR_FLAGS_HIGHLABEL_GAD)
extern const struct FC_Type _MSG_PG_SLIR_FLAGS_IMMEDIATE_GAD;
#define MSG_PG_SLIR_FLAGS_IMMEDIATE_GAD ((APTR) &_MSG_PG_SLIR_FLAGS_IMMEDIATE_GAD)
extern const struct FC_Type _MSG_PG_SLIR_FLAGS_RELVERIFY_GAD;
#define MSG_PG_SLIR_FLAGS_RELVERIFY_GAD ((APTR) &_MSG_PG_SLIR_FLAGS_RELVERIFY_GAD)
extern const struct FC_Type _MSG_PG_SLIR_VAR_MIN_GAD;
#define MSG_PG_SLIR_VAR_MIN_GAD ((APTR) &_MSG_PG_SLIR_VAR_MIN_GAD)
extern const struct FC_Type _MSG_PG_SLIR_VAR_MAX_GAD;
#define MSG_PG_SLIR_VAR_MAX_GAD ((APTR) &_MSG_PG_SLIR_VAR_MAX_GAD)
extern const struct FC_Type _MSG_PG_SLIR_VAR_LEVEL_GAD;
#define MSG_PG_SLIR_VAR_LEVEL_GAD ((APTR) &_MSG_PG_SLIR_VAR_LEVEL_GAD)
extern const struct FC_Type _MSG_PG_SLIR_VAR_MAXLEVLEN_GAD;
#define MSG_PG_SLIR_VAR_MAXLEVLEN_GAD ((APTR) &_MSG_PG_SLIR_VAR_MAXLEVLEN_GAD)
extern const struct FC_Type _MSG_PG_SLIR_VAR_JUSTIFICATION_GAD;
#define MSG_PG_SLIR_VAR_JUSTIFICATION_GAD ((APTR) &_MSG_PG_SLIR_VAR_JUSTIFICATION_GAD)
extern const struct FC_Type _MSG_PG_SLIR_VAR_JUSTIFICATION_L0_GAD;
#define MSG_PG_SLIR_VAR_JUSTIFICATION_L0_GAD ((APTR) &_MSG_PG_SLIR_VAR_JUSTIFICATION_L0_GAD)
extern const struct FC_Type _MSG_PG_SLIR_VAR_JUSTIFICATION_L1_GAD;
#define MSG_PG_SLIR_VAR_JUSTIFICATION_L1_GAD ((APTR) &_MSG_PG_SLIR_VAR_JUSTIFICATION_L1_GAD)
extern const struct FC_Type _MSG_PG_SLIR_VAR_JUSTIFICATION_L2_GAD;
#define MSG_PG_SLIR_VAR_JUSTIFICATION_L2_GAD ((APTR) &_MSG_PG_SLIR_VAR_JUSTIFICATION_L2_GAD)
extern const struct FC_Type _MSG_PG_SLIR_VAR_FREEDOM_GAD;
#define MSG_PG_SLIR_VAR_FREEDOM_GAD ((APTR) &_MSG_PG_SLIR_VAR_FREEDOM_GAD)
extern const struct FC_Type _MSG_PG_SLIR_VAR_FREEDOM_L0_GAD;
#define MSG_PG_SLIR_VAR_FREEDOM_L0_GAD ((APTR) &_MSG_PG_SLIR_VAR_FREEDOM_L0_GAD)
extern const struct FC_Type _MSG_PG_SLIR_VAR_FREEDOM_L1_GAD;
#define MSG_PG_SLIR_VAR_FREEDOM_L1_GAD ((APTR) &_MSG_PG_SLIR_VAR_FREEDOM_L1_GAD)
extern const struct FC_Type _MSG_PG_SLIR_VAR_LEVELPLACE_GAD;
#define MSG_PG_SLIR_VAR_LEVELPLACE_GAD ((APTR) &_MSG_PG_SLIR_VAR_LEVELPLACE_GAD)
extern const struct FC_Type _MSG_PG_SLIR_VAR_LEVELPLACE_L0_GAD;
#define MSG_PG_SLIR_VAR_LEVELPLACE_L0_GAD ((APTR) &_MSG_PG_SLIR_VAR_LEVELPLACE_L0_GAD)
extern const struct FC_Type _MSG_PG_SLIR_VAR_LEVELPLACE_L1_GAD;
#define MSG_PG_SLIR_VAR_LEVELPLACE_L1_GAD ((APTR) &_MSG_PG_SLIR_VAR_LEVELPLACE_L1_GAD)
extern const struct FC_Type _MSG_PG_SLIR_VAR_LEVELPLACE_L2_GAD;
#define MSG_PG_SLIR_VAR_LEVELPLACE_L2_GAD ((APTR) &_MSG_PG_SLIR_VAR_LEVELPLACE_L2_GAD)
extern const struct FC_Type _MSG_PG_SLIR_VAR_LEVELPLACE_L3_GAD;
#define MSG_PG_SLIR_VAR_LEVELPLACE_L3_GAD ((APTR) &_MSG_PG_SLIR_VAR_LEVELPLACE_L3_GAD)
extern const struct FC_Type _MSG_PG_STRG_FLAGS_DISABLED_GAD;
#define MSG_PG_STRG_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_STRG_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_STRG_FLAGS_UNDERSCORE_GAD;
#define MSG_PG_STRG_FLAGS_UNDERSCORE_GAD ((APTR) &_MSG_PG_STRG_FLAGS_UNDERSCORE_GAD)
extern const struct FC_Type _MSG_PG_STRG_FLAGS_HIGHLABEL_GAD;
#define MSG_PG_STRG_FLAGS_HIGHLABEL_GAD ((APTR) &_MSG_PG_STRG_FLAGS_HIGHLABEL_GAD)
extern const struct FC_Type _MSG_PG_STRG_FLAGS_TABCYCLE_GAD;
#define MSG_PG_STRG_FLAGS_TABCYCLE_GAD ((APTR) &_MSG_PG_STRG_FLAGS_TABCYCLE_GAD)
extern const struct FC_Type _MSG_PG_STRG_FLAGS_REPLACEMODE_GAD;
#define MSG_PG_STRG_FLAGS_REPLACEMODE_GAD ((APTR) &_MSG_PG_STRG_FLAGS_REPLACEMODE_GAD)
extern const struct FC_Type _MSG_PG_STRG_FLAGS_EXITHELP_GAD;
#define MSG_PG_STRG_FLAGS_EXITHELP_GAD ((APTR) &_MSG_PG_STRG_FLAGS_EXITHELP_GAD)
extern const struct FC_Type _MSG_PG_STRG_VAR_MAXCHARS_GAD;
#define MSG_PG_STRG_VAR_MAXCHARS_GAD ((APTR) &_MSG_PG_STRG_VAR_MAXCHARS_GAD)
extern const struct FC_Type _MSG_PG_STRG_VAR_STRING_GAD;
#define MSG_PG_STRG_VAR_STRING_GAD ((APTR) &_MSG_PG_STRG_VAR_STRING_GAD)
extern const struct FC_Type _MSG_PG_STRG_VAR_JUSTIFICATION_GAD;
#define MSG_PG_STRG_VAR_JUSTIFICATION_GAD ((APTR) &_MSG_PG_STRG_VAR_JUSTIFICATION_GAD)
extern const struct FC_Type _MSG_PG_STRG_VAR_JUSTIFICATION_L0_GAD;
#define MSG_PG_STRG_VAR_JUSTIFICATION_L0_GAD ((APTR) &_MSG_PG_STRG_VAR_JUSTIFICATION_L0_GAD)
extern const struct FC_Type _MSG_PG_STRG_VAR_JUSTIFICATION_L1_GAD;
#define MSG_PG_STRG_VAR_JUSTIFICATION_L1_GAD ((APTR) &_MSG_PG_STRG_VAR_JUSTIFICATION_L1_GAD)
extern const struct FC_Type _MSG_PG_STRG_VAR_JUSTIFICATION_L2_GAD;
#define MSG_PG_STRG_VAR_JUSTIFICATION_L2_GAD ((APTR) &_MSG_PG_STRG_VAR_JUSTIFICATION_L2_GAD)
extern const struct FC_Type _MSG_PG_TDEK_FLAGS_FRAMES_GAD;
#define MSG_PG_TDEK_FLAGS_FRAMES_GAD ((APTR) &_MSG_PG_TDEK_FLAGS_FRAMES_GAD)
extern const struct FC_Type _MSG_PG_TDEK_FLAGS_CURRENT_GAD;
#define MSG_PG_TDEK_FLAGS_CURRENT_GAD ((APTR) &_MSG_PG_TDEK_FLAGS_CURRENT_GAD)
extern const struct FC_Type _MSG_PG_TDEK_FLAGS_DISABLED_GAD;
#define MSG_PG_TDEK_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_TDEK_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_TDEK_FLAGS_TAPE_GAD;
#define MSG_PG_TDEK_FLAGS_TAPE_GAD ((APTR) &_MSG_PG_TDEK_FLAGS_TAPE_GAD)
extern const struct FC_Type _MSG_PG_TDEK_FLAGS_PAUSED_GAD;
#define MSG_PG_TDEK_FLAGS_PAUSED_GAD ((APTR) &_MSG_PG_TDEK_FLAGS_PAUSED_GAD)
extern const struct FC_Type _MSG_PG_TEXT_FLAGS_DISABLED_GAD;
#define MSG_PG_TEXT_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_TEXT_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_TEXT_FLAGS_HIGHLABEL_GAD;
#define MSG_PG_TEXT_FLAGS_HIGHLABEL_GAD ((APTR) &_MSG_PG_TEXT_FLAGS_HIGHLABEL_GAD)
extern const struct FC_Type _MSG_PG_TEXT_FLAGS_BORDER_GAD;
#define MSG_PG_TEXT_FLAGS_BORDER_GAD ((APTR) &_MSG_PG_TEXT_FLAGS_BORDER_GAD)
extern const struct FC_Type _MSG_PG_TEXT_FLAGS_CLIPPED_GAD;
#define MSG_PG_TEXT_FLAGS_CLIPPED_GAD ((APTR) &_MSG_PG_TEXT_FLAGS_CLIPPED_GAD)
extern const struct FC_Type _MSG_PG_TEXT_FLAGS_COPYTEXT_GAD;
#define MSG_PG_TEXT_FLAGS_COPYTEXT_GAD ((APTR) &_MSG_PG_TEXT_FLAGS_COPYTEXT_GAD)
extern const struct FC_Type _MSG_PG_TEXT_FLAGS_JUSTIFICATION_GAD;
#define MSG_PG_TEXT_FLAGS_JUSTIFICATION_GAD ((APTR) &_MSG_PG_TEXT_FLAGS_JUSTIFICATION_GAD)
extern const struct FC_Type _MSG_PG_TEXT_FLAGS_JUSTIFICATION_L0_GAD;
#define MSG_PG_TEXT_FLAGS_JUSTIFICATION_L0_GAD ((APTR) &_MSG_PG_TEXT_FLAGS_JUSTIFICATION_L0_GAD)
extern const struct FC_Type _MSG_PG_TEXT_FLAGS_JUSTIFICATION_L1_GAD;
#define MSG_PG_TEXT_FLAGS_JUSTIFICATION_L1_GAD ((APTR) &_MSG_PG_TEXT_FLAGS_JUSTIFICATION_L1_GAD)
extern const struct FC_Type _MSG_PG_TEXT_FLAGS_JUSTIFICATION_L2_GAD;
#define MSG_PG_TEXT_FLAGS_JUSTIFICATION_L2_GAD ((APTR) &_MSG_PG_TEXT_FLAGS_JUSTIFICATION_L2_GAD)
extern const struct FC_Type _MSG_PG_TEXT_FLAGS_DEFAULT_GAD;
#define MSG_PG_TEXT_FLAGS_DEFAULT_GAD ((APTR) &_MSG_PG_TEXT_FLAGS_DEFAULT_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_DISABLED_GAD;
#define MSG_PG_TFLD_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_TABCYCLE_GAD;
#define MSG_PG_TFLD_FLAGS_TABCYCLE_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_TABCYCLE_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_READONLY_GAD;
#define MSG_PG_TFLD_FLAGS_READONLY_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_READONLY_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_INVERTED_GAD;
#define MSG_PG_TFLD_FLAGS_INVERTED_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_INVERTED_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_PARTIAL_GAD;
#define MSG_PG_TFLD_FLAGS_PARTIAL_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_PARTIAL_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_BLOCKCURSOR_GAD;
#define MSG_PG_TFLD_FLAGS_BLOCKCURSOR_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_BLOCKCURSOR_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_VCENTER_GAD;
#define MSG_PG_TFLD_FLAGS_VCENTER_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_VCENTER_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_PASSCOMMAND_GAD;
#define MSG_PG_TFLD_FLAGS_PASSCOMMAND_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_PASSCOMMAND_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_CLIPBOARD_GAD;
#define MSG_PG_TFLD_FLAGS_CLIPBOARD_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_CLIPBOARD_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_UNDO_GAD;
#define MSG_PG_TFLD_FLAGS_UNDO_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_UNDO_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_NONPRINTCHARS_GAD;
#define MSG_PG_TFLD_FLAGS_NONPRINTCHARS_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_NONPRINTCHARS_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_MAXSIZEBEEP_GAD;
#define MSG_PG_TFLD_FLAGS_MAXSIZEBEEP_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_MAXSIZEBEEP_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_NOGHOST_GAD;
#define MSG_PG_TFLD_FLAGS_NOGHOST_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_NOGHOST_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_MODIFIED_GAD;
#define MSG_PG_TFLD_FLAGS_MODIFIED_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_MODIFIED_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_USERALIGN_GAD;
#define MSG_PG_TFLD_FLAGS_USERALIGN_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_USERALIGN_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_RULEDPAPER_GAD;
#define MSG_PG_TFLD_FLAGS_RULEDPAPER_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_RULEDPAPER_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_BORDER_GAD;
#define MSG_PG_TFLD_FLAGS_BORDER_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_BORDER_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_BORDER_L0_GAD;
#define MSG_PG_TFLD_FLAGS_BORDER_L0_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_BORDER_L0_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_BORDER_L1_GAD;
#define MSG_PG_TFLD_FLAGS_BORDER_L1_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_BORDER_L1_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_BORDER_L2_GAD;
#define MSG_PG_TFLD_FLAGS_BORDER_L2_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_BORDER_L2_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_ALIGN_GAD;
#define MSG_PG_TFLD_FLAGS_ALIGN_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_ALIGN_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_ALIGN_L0_GAD;
#define MSG_PG_TFLD_FLAGS_ALIGN_L0_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_ALIGN_L0_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_ALIGN_L1_GAD;
#define MSG_PG_TFLD_FLAGS_ALIGN_L1_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_ALIGN_L1_GAD)
extern const struct FC_Type _MSG_PG_TFLD_FLAGS_ALIGN_L2_GAD;
#define MSG_PG_TFLD_FLAGS_ALIGN_L2_GAD ((APTR) &_MSG_PG_TFLD_FLAGS_ALIGN_L2_GAD)
extern const struct FC_Type _MSG_PG_TFLD_VAR_BLINKRATE_GAD;
#define MSG_PG_TFLD_VAR_BLINKRATE_GAD ((APTR) &_MSG_PG_TFLD_VAR_BLINKRATE_GAD)
extern const struct FC_Type _MSG_PG_TFLD_VAR_MAXSIZE_GAD;
#define MSG_PG_TFLD_VAR_MAXSIZE_GAD ((APTR) &_MSG_PG_TFLD_VAR_MAXSIZE_GAD)
extern const struct FC_Type _MSG_PG_TFLD_VAR_TABSPACES_GAD;
#define MSG_PG_TFLD_VAR_TABSPACES_GAD ((APTR) &_MSG_PG_TFLD_VAR_TABSPACES_GAD)
extern const struct FC_Type _MSG_PG_TFLD_VAR_SPACING_GAD;
#define MSG_PG_TFLD_VAR_SPACING_GAD ((APTR) &_MSG_PG_TFLD_VAR_SPACING_GAD)
extern const struct FC_Type _MSG_PG_TFLD_VAR_DELIMITERS_GAD;
#define MSG_PG_TFLD_VAR_DELIMITERS_GAD ((APTR) &_MSG_PG_TFLD_VAR_DELIMITERS_GAD)
extern const struct FC_Type _MSG_PG_TFLD_VAR_ACCEPTCHARS_GAD;
#define MSG_PG_TFLD_VAR_ACCEPTCHARS_GAD ((APTR) &_MSG_PG_TFLD_VAR_ACCEPTCHARS_GAD)
extern const struct FC_Type _MSG_PG_TFLD_VAR_REJECTCHARS_GAD;
#define MSG_PG_TFLD_VAR_REJECTCHARS_GAD ((APTR) &_MSG_PG_TFLD_VAR_REJECTCHARS_GAD)
extern const struct FC_Type _MSG_Properties_WND;
#define MSG_Properties_WND ((APTR) &_MSG_Properties_WND)
extern const struct FC_Type _MSG_PROPERTIES_LOCK_GAD;
#define MSG_PROPERTIES_LOCK_GAD ((APTR) &_MSG_PROPERTIES_LOCK_GAD)
extern const struct FC_Type _MSG_PROPERTIES_APPLY_GAD;
#define MSG_PROPERTIES_APPLY_GAD ((APTR) &_MSG_PROPERTIES_APPLY_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L0_GAD;
#define MSG_PROPERTIES_PAGES_L0_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L0_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L1_GAD;
#define MSG_PROPERTIES_PAGES_L1_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L1_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L2_GAD;
#define MSG_PROPERTIES_PAGES_L2_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L2_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L3_GAD;
#define MSG_PROPERTIES_PAGES_L3_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L3_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L4_GAD;
#define MSG_PROPERTIES_PAGES_L4_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L4_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L5_GAD;
#define MSG_PROPERTIES_PAGES_L5_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L5_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L6_GAD;
#define MSG_PROPERTIES_PAGES_L6_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L6_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L7_GAD;
#define MSG_PROPERTIES_PAGES_L7_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L7_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L8_GAD;
#define MSG_PROPERTIES_PAGES_L8_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L8_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L9_GAD;
#define MSG_PROPERTIES_PAGES_L9_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L9_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L10_GAD;
#define MSG_PROPERTIES_PAGES_L10_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L10_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L11_GAD;
#define MSG_PROPERTIES_PAGES_L11_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L11_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L12_GAD;
#define MSG_PROPERTIES_PAGES_L12_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L12_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L13_GAD;
#define MSG_PROPERTIES_PAGES_L13_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L13_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L14_GAD;
#define MSG_PROPERTIES_PAGES_L14_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L14_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L15_GAD;
#define MSG_PROPERTIES_PAGES_L15_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L15_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L16_GAD;
#define MSG_PROPERTIES_PAGES_L16_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L16_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L17_GAD;
#define MSG_PROPERTIES_PAGES_L17_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L17_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L18_GAD;
#define MSG_PROPERTIES_PAGES_L18_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L18_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L19_GAD;
#define MSG_PROPERTIES_PAGES_L19_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L19_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L20_GAD;
#define MSG_PROPERTIES_PAGES_L20_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L20_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L21_GAD;
#define MSG_PROPERTIES_PAGES_L21_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L21_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L22_GAD;
#define MSG_PROPERTIES_PAGES_L22_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L22_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L23_GAD;
#define MSG_PROPERTIES_PAGES_L23_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L23_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L24_GAD;
#define MSG_PROPERTIES_PAGES_L24_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L24_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L25_GAD;
#define MSG_PROPERTIES_PAGES_L25_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L25_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L26_GAD;
#define MSG_PROPERTIES_PAGES_L26_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L26_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L27_GAD;
#define MSG_PROPERTIES_PAGES_L27_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L27_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L28_GAD;
#define MSG_PROPERTIES_PAGES_L28_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L28_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L29_GAD;
#define MSG_PROPERTIES_PAGES_L29_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L29_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L30_GAD;
#define MSG_PROPERTIES_PAGES_L30_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L30_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L31_GAD;
#define MSG_PROPERTIES_PAGES_L31_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L31_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L32_GAD;
#define MSG_PROPERTIES_PAGES_L32_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L32_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L33_GAD;
#define MSG_PROPERTIES_PAGES_L33_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L33_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L34_GAD;
#define MSG_PROPERTIES_PAGES_L34_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L34_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L35_GAD;
#define MSG_PROPERTIES_PAGES_L35_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L35_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L36_GAD;
#define MSG_PROPERTIES_PAGES_L36_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L36_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L37_GAD;
#define MSG_PROPERTIES_PAGES_L37_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L37_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L38_GAD;
#define MSG_PROPERTIES_PAGES_L38_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L38_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L39_GAD;
#define MSG_PROPERTIES_PAGES_L39_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L39_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L40_GAD;
#define MSG_PROPERTIES_PAGES_L40_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L40_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L41_GAD;
#define MSG_PROPERTIES_PAGES_L41_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L41_GAD)
extern const struct FC_Type _MSG_PROPERTIES_PAGES_L42_GAD;
#define MSG_PROPERTIES_PAGES_L42_GAD ((APTR) &_MSG_PROPERTIES_PAGES_L42_GAD)
extern const struct FC_Type _MSG_Edit_WND;
#define MSG_Edit_WND ((APTR) &_MSG_Edit_WND)
extern const struct FC_Type _MSG_Preferences_WND;
#define MSG_Preferences_WND ((APTR) &_MSG_Preferences_WND)
extern const struct FC_Type _MSG_PREFS_SAVE_GAD;
#define MSG_PREFS_SAVE_GAD ((APTR) &_MSG_PREFS_SAVE_GAD)
extern const struct FC_Type _MSG_PREFS_USE_GAD;
#define MSG_PREFS_USE_GAD ((APTR) &_MSG_PREFS_USE_GAD)
extern const struct FC_Type _MSG_PREFS_CANCEL_GAD;
#define MSG_PREFS_CANCEL_GAD ((APTR) &_MSG_PREFS_CANCEL_GAD)
extern const struct FC_Type _MSG_PG_PREFS_GENERAL_AUTOBACKUP_GAD;
#define MSG_PG_PREFS_GENERAL_AUTOBACKUP_GAD ((APTR) &_MSG_PG_PREFS_GENERAL_AUTOBACKUP_GAD)
extern const struct FC_Type _MSG_PG_PREFS_GENERAL_SIZEZOOM_GAD;
#define MSG_PG_PREFS_GENERAL_SIZEZOOM_GAD ((APTR) &_MSG_PG_PREFS_GENERAL_SIZEZOOM_GAD)
extern const struct FC_Type _MSG_PG_PREFS_GENERAL_FASTREDRAW_GAD;
#define MSG_PG_PREFS_GENERAL_FASTREDRAW_GAD ((APTR) &_MSG_PG_PREFS_GENERAL_FASTREDRAW_GAD)
extern const struct FC_Type _MSG_PG_PREFS_GENERAL_GETSCREEN_GAD;
#define MSG_PG_PREFS_GENERAL_GETSCREEN_GAD ((APTR) &_MSG_PG_PREFS_GENERAL_GETSCREEN_GAD)
extern const struct FC_Type _MSG_PG_PREFS_GENERAL_SCREENMODE_GAD;
#define MSG_PG_PREFS_GENERAL_SCREENMODE_GAD ((APTR) &_MSG_PG_PREFS_GENERAL_SCREENMODE_GAD)
extern const struct FC_Type _MSG_PG_PREFS_GEN_LIST_GAD;
#define MSG_PG_PREFS_GEN_LIST_GAD ((APTR) &_MSG_PG_PREFS_GEN_LIST_GAD)
extern const struct FC_Type _MSG_PG_PREFS_GENERAL_FONTNAME_GAD;
#define MSG_PG_PREFS_GENERAL_FONTNAME_GAD ((APTR) &_MSG_PG_PREFS_GENERAL_FONTNAME_GAD)
extern const struct FC_Type _MSG_PG_PREFS_GENERAL_EDITFONT_GAD;
#define MSG_PG_PREFS_GENERAL_EDITFONT_GAD ((APTR) &_MSG_PG_PREFS_GENERAL_EDITFONT_GAD)
extern const struct FC_Type _MSG_Grid_WND;
#define MSG_Grid_WND ((APTR) &_MSG_Grid_WND)
extern const struct FC_Type _MSG_GRID_X_GAD;
#define MSG_GRID_X_GAD ((APTR) &_MSG_GRID_X_GAD)
extern const struct FC_Type _MSG_GRID_Y_GAD;
#define MSG_GRID_Y_GAD ((APTR) &_MSG_GRID_Y_GAD)
extern const struct FC_Type _MSG_GRID_SHOW_GAD;
#define MSG_GRID_SHOW_GAD ((APTR) &_MSG_GRID_SHOW_GAD)
extern const struct FC_Type _MSG_GRID_SNAP_GAD;
#define MSG_GRID_SNAP_GAD ((APTR) &_MSG_GRID_SNAP_GAD)
extern const struct FC_Type _MSG_GRID_OK_GAD;
#define MSG_GRID_OK_GAD ((APTR) &_MSG_GRID_OK_GAD)
extern const struct FC_Type _MSG_GRID_CANCEL_GAD;
#define MSG_GRID_CANCEL_GAD ((APTR) &_MSG_GRID_CANCEL_GAD)
extern const struct FC_Type _MSG_PGWN_LABEL_GAD;
#define MSG_PGWN_LABEL_GAD ((APTR) &_MSG_PGWN_LABEL_GAD)
extern const struct FC_Type _MSG_PGWN_X_GAD;
#define MSG_PGWN_X_GAD ((APTR) &_MSG_PGWN_X_GAD)
extern const struct FC_Type _MSG_PGWN_Y_GAD;
#define MSG_PGWN_Y_GAD ((APTR) &_MSG_PGWN_Y_GAD)
extern const struct FC_Type _MSG_PGWN_WIDTH_GAD;
#define MSG_PGWN_WIDTH_GAD ((APTR) &_MSG_PGWN_WIDTH_GAD)
extern const struct FC_Type _MSG_PGWN_HEIGHT_GAD;
#define MSG_PGWN_HEIGHT_GAD ((APTR) &_MSG_PGWN_HEIGHT_GAD)
extern const struct FC_Type _MSG_PGWN_INNERHEIGHT_GAD;
#define MSG_PGWN_INNERHEIGHT_GAD ((APTR) &_MSG_PGWN_INNERHEIGHT_GAD)
extern const struct FC_Type _MSG_PGWN_INNERWIDTH_GAD;
#define MSG_PGWN_INNERWIDTH_GAD ((APTR) &_MSG_PGWN_INNERWIDTH_GAD)
extern const struct FC_Type _MSG_PGWN_REL_H_GAD;
#define MSG_PGWN_REL_H_GAD ((APTR) &_MSG_PGWN_REL_H_GAD)
extern const struct FC_Type _MSG_PGWN_REL_H_L0_GAD;
#define MSG_PGWN_REL_H_L0_GAD ((APTR) &_MSG_PGWN_REL_H_L0_GAD)
extern const struct FC_Type _MSG_PGWN_REL_H_L1_GAD;
#define MSG_PGWN_REL_H_L1_GAD ((APTR) &_MSG_PGWN_REL_H_L1_GAD)
extern const struct FC_Type _MSG_PGWN_REL_W_GAD;
#define MSG_PGWN_REL_W_GAD ((APTR) &_MSG_PGWN_REL_W_GAD)
extern const struct FC_Type _MSG_PGWN_REL_W_L0_GAD;
#define MSG_PGWN_REL_W_L0_GAD ((APTR) &_MSG_PGWN_REL_W_L0_GAD)
extern const struct FC_Type _MSG_PGWN_REL_W_L1_GAD;
#define MSG_PGWN_REL_W_L1_GAD ((APTR) &_MSG_PGWN_REL_W_L1_GAD)
extern const struct FC_Type _MSG_PGWN_REL_Y_GAD;
#define MSG_PGWN_REL_Y_GAD ((APTR) &_MSG_PGWN_REL_Y_GAD)
extern const struct FC_Type _MSG_PGWN_REL_Y_L0_GAD;
#define MSG_PGWN_REL_Y_L0_GAD ((APTR) &_MSG_PGWN_REL_Y_L0_GAD)
extern const struct FC_Type _MSG_PGWN_REL_Y_L1_GAD;
#define MSG_PGWN_REL_Y_L1_GAD ((APTR) &_MSG_PGWN_REL_Y_L1_GAD)
extern const struct FC_Type _MSG_PGWN_REL_Y_L2_GAD;
#define MSG_PGWN_REL_Y_L2_GAD ((APTR) &_MSG_PGWN_REL_Y_L2_GAD)
extern const struct FC_Type _MSG_PGWN_REL_X_GAD;
#define MSG_PGWN_REL_X_GAD ((APTR) &_MSG_PGWN_REL_X_GAD)
extern const struct FC_Type _MSG_PGWN_REL_X_L0_GAD;
#define MSG_PGWN_REL_X_L0_GAD ((APTR) &_MSG_PGWN_REL_X_L0_GAD)
extern const struct FC_Type _MSG_PGWN_REL_X_L1_GAD;
#define MSG_PGWN_REL_X_L1_GAD ((APTR) &_MSG_PGWN_REL_X_L1_GAD)
extern const struct FC_Type _MSG_PGWN_REL_X_L2_GAD;
#define MSG_PGWN_REL_X_L2_GAD ((APTR) &_MSG_PGWN_REL_X_L2_GAD)
extern const struct FC_Type _MSG_PGWN_SCREEN_TITLE_GAD;
#define MSG_PGWN_SCREEN_TITLE_GAD ((APTR) &_MSG_PGWN_SCREEN_TITLE_GAD)
extern const struct FC_Type _MSG_PGWN_WINDOW_TITLE_GAD;
#define MSG_PGWN_WINDOW_TITLE_GAD ((APTR) &_MSG_PGWN_WINDOW_TITLE_GAD)
extern const struct FC_Type _MSG_PGWN_PAGED_GAD;
#define MSG_PGWN_PAGED_GAD ((APTR) &_MSG_PGWN_PAGED_GAD)
extern const struct FC_Type _MSG_PGWN_FONTADAPTIVE_GAD;
#define MSG_PGWN_FONTADAPTIVE_GAD ((APTR) &_MSG_PGWN_FONTADAPTIVE_GAD)
extern const struct FC_Type _MSG_PGWN_APPWINDOW_GAD;
#define MSG_PGWN_APPWINDOW_GAD ((APTR) &_MSG_PGWN_APPWINDOW_GAD)
extern const struct FC_Type _MSG_PGWN_PROJECT_GAD;
#define MSG_PGWN_PROJECT_GAD ((APTR) &_MSG_PGWN_PROJECT_GAD)
extern const struct FC_Type _MSG_PGWN_MENU_GET_GAD;
#define MSG_PGWN_MENU_GET_GAD ((APTR) &_MSG_PGWN_MENU_GET_GAD)
extern const struct FC_Type _MSG_PGWN_MENU_GAD;
#define MSG_PGWN_MENU_GAD ((APTR) &_MSG_PGWN_MENU_GAD)
extern const struct FC_Type _MSG_PGWN_ZOOM_GAD;
#define MSG_PGWN_ZOOM_GAD ((APTR) &_MSG_PGWN_ZOOM_GAD)
extern const struct FC_Type _MSG_PGWN_BACKDROP_GAD;
#define MSG_PGWN_BACKDROP_GAD ((APTR) &_MSG_PGWN_BACKDROP_GAD)
extern const struct FC_Type _MSG_PGWN_BORDERLESS_GAD;
#define MSG_PGWN_BORDERLESS_GAD ((APTR) &_MSG_PGWN_BORDERLESS_GAD)
extern const struct FC_Type _MSG_PGWN_SIZEBBOTTOM_GAD;
#define MSG_PGWN_SIZEBBOTTOM_GAD ((APTR) &_MSG_PGWN_SIZEBBOTTOM_GAD)
extern const struct FC_Type _MSG_PGWN_SIZEBRIGHT_GAD;
#define MSG_PGWN_SIZEBRIGHT_GAD ((APTR) &_MSG_PGWN_SIZEBRIGHT_GAD)
extern const struct FC_Type _MSG_PGWN_CLOSEGADGET_GAD;
#define MSG_PGWN_CLOSEGADGET_GAD ((APTR) &_MSG_PGWN_CLOSEGADGET_GAD)
extern const struct FC_Type _MSG_PGWN_DEPTHGADGET_GAD;
#define MSG_PGWN_DEPTHGADGET_GAD ((APTR) &_MSG_PGWN_DEPTHGADGET_GAD)
extern const struct FC_Type _MSG_PGWN_SIZEGADGET_GAD;
#define MSG_PGWN_SIZEGADGET_GAD ((APTR) &_MSG_PGWN_SIZEGADGET_GAD)
extern const struct FC_Type _MSG_PGWN_DRAGGADGET_GAD;
#define MSG_PGWN_DRAGGADGET_GAD ((APTR) &_MSG_PGWN_DRAGGADGET_GAD)
extern const struct FC_Type _MSG_PGWN_DRAGGADGET_L0_GAD;
#define MSG_PGWN_DRAGGADGET_L0_GAD ((APTR) &_MSG_PGWN_DRAGGADGET_L0_GAD)
extern const struct FC_Type _MSG_PGWN_DRAGGADGET_L1_GAD;
#define MSG_PGWN_DRAGGADGET_L1_GAD ((APTR) &_MSG_PGWN_DRAGGADGET_L1_GAD)
extern const struct FC_Type _MSG_PGWN_DRAGGADGET_L2_GAD;
#define MSG_PGWN_DRAGGADGET_L2_GAD ((APTR) &_MSG_PGWN_DRAGGADGET_L2_GAD)
extern const struct FC_Type _MSG_PGWN_DRAGGADGET_L3_GAD;
#define MSG_PGWN_DRAGGADGET_L3_GAD ((APTR) &_MSG_PGWN_DRAGGADGET_L3_GAD)
extern const struct FC_Type _MSG_PGWN_FALLBACK_GAD;
#define MSG_PGWN_FALLBACK_GAD ((APTR) &_MSG_PGWN_FALLBACK_GAD)
extern const struct FC_Type _MSG_PGWN_REPORTMOUSE_GAD;
#define MSG_PGWN_REPORTMOUSE_GAD ((APTR) &_MSG_PGWN_REPORTMOUSE_GAD)
extern const struct FC_Type _MSG_PGWN_AUTOADJUST_GAD;
#define MSG_PGWN_AUTOADJUST_GAD ((APTR) &_MSG_PGWN_AUTOADJUST_GAD)
extern const struct FC_Type _MSG_PGWN_ACTIVATE_GAD;
#define MSG_PGWN_ACTIVATE_GAD ((APTR) &_MSG_PGWN_ACTIVATE_GAD)
extern const struct FC_Type _MSG_PGWN_RMBTRAP_GAD;
#define MSG_PGWN_RMBTRAP_GAD ((APTR) &_MSG_PGWN_RMBTRAP_GAD)
extern const struct FC_Type _MSG_PGWN_NEWLOOKMENUS_GAD;
#define MSG_PGWN_NEWLOOKMENUS_GAD ((APTR) &_MSG_PGWN_NEWLOOKMENUS_GAD)
extern const struct FC_Type _MSG_PGWN_NOCAREREFRESH_GAD;
#define MSG_PGWN_NOCAREREFRESH_GAD ((APTR) &_MSG_PGWN_NOCAREREFRESH_GAD)
extern const struct FC_Type _MSG_PGWN_GZZ_GAD;
#define MSG_PGWN_GZZ_GAD ((APTR) &_MSG_PGWN_GZZ_GAD)
extern const struct FC_Type _MSG_PGWN_REFRESH_GAD;
#define MSG_PGWN_REFRESH_GAD ((APTR) &_MSG_PGWN_REFRESH_GAD)
extern const struct FC_Type _MSG_PGWN_REFRESH_L0_GAD;
#define MSG_PGWN_REFRESH_L0_GAD ((APTR) &_MSG_PGWN_REFRESH_L0_GAD)
extern const struct FC_Type _MSG_PGWN_REFRESH_L1_GAD;
#define MSG_PGWN_REFRESH_L1_GAD ((APTR) &_MSG_PGWN_REFRESH_L1_GAD)
extern const struct FC_Type _MSG_PGWN_REFRESH_L2_GAD;
#define MSG_PGWN_REFRESH_L2_GAD ((APTR) &_MSG_PGWN_REFRESH_L2_GAD)
extern const struct FC_Type _MSG_PGWN_MOUSEQUEUE_GAD;
#define MSG_PGWN_MOUSEQUEUE_GAD ((APTR) &_MSG_PGWN_MOUSEQUEUE_GAD)
extern const struct FC_Type _MSG_PGWN_REPEATQUEUE_GAD;
#define MSG_PGWN_REPEATQUEUE_GAD ((APTR) &_MSG_PGWN_REPEATQUEUE_GAD)
extern const struct FC_Type _MSG_PGWN_IDCMP_GAD;
#define MSG_PGWN_IDCMP_GAD ((APTR) &_MSG_PGWN_IDCMP_GAD)
extern const struct FC_Type _MSG_PGWN_REPEATQUEUE_SET_GAD;
#define MSG_PGWN_REPEATQUEUE_SET_GAD ((APTR) &_MSG_PGWN_REPEATQUEUE_SET_GAD)
extern const struct FC_Type _MSG_PGWN_MOUSEQUEUE_SET_GAD;
#define MSG_PGWN_MOUSEQUEUE_SET_GAD ((APTR) &_MSG_PGWN_MOUSEQUEUE_SET_GAD)
extern const struct FC_Type _MSG_PGWN_NOTIFYDEPTH_GAD;
#define MSG_PGWN_NOTIFYDEPTH_GAD ((APTR) &_MSG_PGWN_NOTIFYDEPTH_GAD)
extern const struct FC_Type _MSG_PGWN_MENUHELP_GAD;
#define MSG_PGWN_MENUHELP_GAD ((APTR) &_MSG_PGWN_MENUHELP_GAD)
extern const struct FC_Type _MSG_PGWN_POINTERDELAY_GAD;
#define MSG_PGWN_POINTERDELAY_GAD ((APTR) &_MSG_PGWN_POINTERDELAY_GAD)
extern const struct FC_Type _MSG_WN_IDCMPFlags_WND;
#define MSG_WN_IDCMPFlags_WND ((APTR) &_MSG_WN_IDCMPFlags_WND)
extern const struct FC_Type _MSG_IDCMP_CANCEL_GAD;
#define MSG_IDCMP_CANCEL_GAD ((APTR) &_MSG_IDCMP_CANCEL_GAD)
extern const struct FC_Type _MSG_IDCMP_OK_GAD;
#define MSG_IDCMP_OK_GAD ((APTR) &_MSG_IDCMP_OK_GAD)
extern const struct FC_Type _MSG_IDCMP_MENUPICK_GAD;
#define MSG_IDCMP_MENUPICK_GAD ((APTR) &_MSG_IDCMP_MENUPICK_GAD)
extern const struct FC_Type _MSG_IDCMP_GADGETHELP_GAD;
#define MSG_IDCMP_GADGETHELP_GAD ((APTR) &_MSG_IDCMP_GADGETHELP_GAD)
extern const struct FC_Type _MSG_IDCMP_MENUHELP_GAD;
#define MSG_IDCMP_MENUHELP_GAD ((APTR) &_MSG_IDCMP_MENUHELP_GAD)
extern const struct FC_Type _MSG_IDCMP_IDCMPUPDATE_GAD;
#define MSG_IDCMP_IDCMPUPDATE_GAD ((APTR) &_MSG_IDCMP_IDCMPUPDATE_GAD)
extern const struct FC_Type _MSG_IDCMP_DISKINSERTED_GAD;
#define MSG_IDCMP_DISKINSERTED_GAD ((APTR) &_MSG_IDCMP_DISKINSERTED_GAD)
extern const struct FC_Type _MSG_IDCMP_DISKREMOVED_GAD;
#define MSG_IDCMP_DISKREMOVED_GAD ((APTR) &_MSG_IDCMP_DISKREMOVED_GAD)
extern const struct FC_Type _MSG_IDCMP_INACTIVEWINDOW_GAD;
#define MSG_IDCMP_INACTIVEWINDOW_GAD ((APTR) &_MSG_IDCMP_INACTIVEWINDOW_GAD)
extern const struct FC_Type _MSG_IDCMP_ACTIVEWINDOW_GAD;
#define MSG_IDCMP_ACTIVEWINDOW_GAD ((APTR) &_MSG_IDCMP_ACTIVEWINDOW_GAD)
extern const struct FC_Type _MSG_IDCMP_INTUITICKS_GAD;
#define MSG_IDCMP_INTUITICKS_GAD ((APTR) &_MSG_IDCMP_INTUITICKS_GAD)
extern const struct FC_Type _MSG_IDCMP_CLOSEWINDOW_GAD;
#define MSG_IDCMP_CLOSEWINDOW_GAD ((APTR) &_MSG_IDCMP_CLOSEWINDOW_GAD)
extern const struct FC_Type _MSG_IDCMP_VANILLAKEY_GAD;
#define MSG_IDCMP_VANILLAKEY_GAD ((APTR) &_MSG_IDCMP_VANILLAKEY_GAD)
extern const struct FC_Type _MSG_IDCMP_RAWKEY_GAD;
#define MSG_IDCMP_RAWKEY_GAD ((APTR) &_MSG_IDCMP_RAWKEY_GAD)
extern const struct FC_Type _MSG_IDCMP_GADGETDOWN_GAD;
#define MSG_IDCMP_GADGETDOWN_GAD ((APTR) &_MSG_IDCMP_GADGETDOWN_GAD)
extern const struct FC_Type _MSG_IDCMP_GADGETUP_GAD;
#define MSG_IDCMP_GADGETUP_GAD ((APTR) &_MSG_IDCMP_GADGETUP_GAD)
extern const struct FC_Type _MSG_IDCMP_MOUSEBUTTONS_GAD;
#define MSG_IDCMP_MOUSEBUTTONS_GAD ((APTR) &_MSG_IDCMP_MOUSEBUTTONS_GAD)
extern const struct FC_Type _MSG_IDCMP_NEWPREFS_GAD;
#define MSG_IDCMP_NEWPREFS_GAD ((APTR) &_MSG_IDCMP_NEWPREFS_GAD)
extern const struct FC_Type _MSG_IDCMP_CHANGEWINDOW_GAD;
#define MSG_IDCMP_CHANGEWINDOW_GAD ((APTR) &_MSG_IDCMP_CHANGEWINDOW_GAD)
extern const struct FC_Type _MSG_IDCMP_REFRESHWINDOW_GAD;
#define MSG_IDCMP_REFRESHWINDOW_GAD ((APTR) &_MSG_IDCMP_REFRESHWINDOW_GAD)
extern const struct FC_Type _MSG_IDCMP_NEWSIZE_GAD;
#define MSG_IDCMP_NEWSIZE_GAD ((APTR) &_MSG_IDCMP_NEWSIZE_GAD)
extern const struct FC_Type _MSG_IDCMP_REQCLEAR_GAD;
#define MSG_IDCMP_REQCLEAR_GAD ((APTR) &_MSG_IDCMP_REQCLEAR_GAD)
extern const struct FC_Type _MSG_IDCMP_REQSET_GAD;
#define MSG_IDCMP_REQSET_GAD ((APTR) &_MSG_IDCMP_REQSET_GAD)
extern const struct FC_Type _MSG_IDCMP_REQVERIFY_GAD;
#define MSG_IDCMP_REQVERIFY_GAD ((APTR) &_MSG_IDCMP_REQVERIFY_GAD)
extern const struct FC_Type _MSG_IDCMP_SIZEVERIFY_GAD;
#define MSG_IDCMP_SIZEVERIFY_GAD ((APTR) &_MSG_IDCMP_SIZEVERIFY_GAD)
extern const struct FC_Type _MSG_IDCMP_MENUVERIFY_GAD;
#define MSG_IDCMP_MENUVERIFY_GAD ((APTR) &_MSG_IDCMP_MENUVERIFY_GAD)
extern const struct FC_Type _MSG_IDCMP_MOUSEMOVE_GAD;
#define MSG_IDCMP_MOUSEMOVE_GAD ((APTR) &_MSG_IDCMP_MOUSEMOVE_GAD)
extern const struct FC_Type _MSG_IDCMP_DELTAMOVE_GAD;
#define MSG_IDCMP_DELTAMOVE_GAD ((APTR) &_MSG_IDCMP_DELTAMOVE_GAD)
extern const struct FC_Type _MSG_PGMN_LABEL_GAD;
#define MSG_PGMN_LABEL_GAD ((APTR) &_MSG_PGMN_LABEL_GAD)
extern const struct FC_Type _MSG_PGMN_NEWLOOK_GAD;
#define MSG_PGMN_NEWLOOK_GAD ((APTR) &_MSG_PGMN_NEWLOOK_GAD)
extern const struct FC_Type _MSG_Working_WND;
#define MSG_Working_WND ((APTR) &_MSG_Working_WND)
extern const struct FC_Type _MSG_WORK_PROGRESS_FORMAT_GAD;
#define MSG_WORK_PROGRESS_FORMAT_GAD ((APTR) &_MSG_WORK_PROGRESS_FORMAT_GAD)
extern const struct FC_Type _MSG_PGFR_X_GAD;
#define MSG_PGFR_X_GAD ((APTR) &_MSG_PGFR_X_GAD)
extern const struct FC_Type _MSG_PGFR_Y_GAD;
#define MSG_PGFR_Y_GAD ((APTR) &_MSG_PGFR_Y_GAD)
extern const struct FC_Type _MSG_PGFR_WIDTH_GAD;
#define MSG_PGFR_WIDTH_GAD ((APTR) &_MSG_PGFR_WIDTH_GAD)
extern const struct FC_Type _MSG_PGFR_HEIGHT_GAD;
#define MSG_PGFR_HEIGHT_GAD ((APTR) &_MSG_PGFR_HEIGHT_GAD)
extern const struct FC_Type _MSG_PGFR_FRAME_GAD;
#define MSG_PGFR_FRAME_GAD ((APTR) &_MSG_PGFR_FRAME_GAD)
extern const struct FC_Type _MSG_PGFR_FRAME_L0_GAD;
#define MSG_PGFR_FRAME_L0_GAD ((APTR) &_MSG_PGFR_FRAME_L0_GAD)
extern const struct FC_Type _MSG_PGFR_FRAME_L1_GAD;
#define MSG_PGFR_FRAME_L1_GAD ((APTR) &_MSG_PGFR_FRAME_L1_GAD)
extern const struct FC_Type _MSG_PGFR_FRAME_L2_GAD;
#define MSG_PGFR_FRAME_L2_GAD ((APTR) &_MSG_PGFR_FRAME_L2_GAD)
extern const struct FC_Type _MSG_PGFR_FRAME_L3_GAD;
#define MSG_PGFR_FRAME_L3_GAD ((APTR) &_MSG_PGFR_FRAME_L3_GAD)
extern const struct FC_Type _MSG_PGFR_FRAME_L4_GAD;
#define MSG_PGFR_FRAME_L4_GAD ((APTR) &_MSG_PGFR_FRAME_L4_GAD)
extern const struct FC_Type _MSG_PGFR_RECESSED_GAD;
#define MSG_PGFR_RECESSED_GAD ((APTR) &_MSG_PGFR_RECESSED_GAD)
extern const struct FC_Type _MSG_EditMenu_WND;
#define MSG_EditMenu_WND ((APTR) &_MSG_EditMenu_WND)
extern const struct FC_Type _MSG_EditImage_WND;
#define MSG_EditImage_WND ((APTR) &_MSG_EditImage_WND)
extern const struct FC_Type _MSG_List_WND;
#define MSG_List_WND ((APTR) &_MSG_List_WND)
extern const struct FC_Type _MSG_LIST_GAD;
#define MSG_LIST_GAD ((APTR) &_MSG_LIST_GAD)
extern const struct FC_Type _MSG_PGMN_ITEM_LABEL_GAD;
#define MSG_PGMN_ITEM_LABEL_GAD ((APTR) &_MSG_PGMN_ITEM_LABEL_GAD)
extern const struct FC_Type _MSG_PGMN_ITEM_TITLE_GAD;
#define MSG_PGMN_ITEM_TITLE_GAD ((APTR) &_MSG_PGMN_ITEM_TITLE_GAD)
extern const struct FC_Type _MSG_PGMN_ITEM_COMMKEY_GAD;
#define MSG_PGMN_ITEM_COMMKEY_GAD ((APTR) &_MSG_PGMN_ITEM_COMMKEY_GAD)
extern const struct FC_Type _MSG_PGMN_ITEM_POPUP_GAD;
#define MSG_PGMN_ITEM_POPUP_GAD ((APTR) &_MSG_PGMN_ITEM_POPUP_GAD)
extern const struct FC_Type _MSG_PGMN_ITEM_BARLABEL_GAD;
#define MSG_PGMN_ITEM_BARLABEL_GAD ((APTR) &_MSG_PGMN_ITEM_BARLABEL_GAD)
extern const struct FC_Type _MSG_PGMN_ITEM_DISABLED_GAD;
#define MSG_PGMN_ITEM_DISABLED_GAD ((APTR) &_MSG_PGMN_ITEM_DISABLED_GAD)
extern const struct FC_Type _MSG_PGMN_ITEM_CHECKED_GAD;
#define MSG_PGMN_ITEM_CHECKED_GAD ((APTR) &_MSG_PGMN_ITEM_CHECKED_GAD)
extern const struct FC_Type _MSG_PGMN_ITEM_TOGGLE_GAD;
#define MSG_PGMN_ITEM_TOGGLE_GAD ((APTR) &_MSG_PGMN_ITEM_TOGGLE_GAD)
extern const struct FC_Type _MSG_PGPI_LABEL_GAD;
#define MSG_PGPI_LABEL_GAD ((APTR) &_MSG_PGPI_LABEL_GAD)
extern const struct FC_Type _MSG_PGPI_WIDTH_GAD;
#define MSG_PGPI_WIDTH_GAD ((APTR) &_MSG_PGPI_WIDTH_GAD)
extern const struct FC_Type _MSG_PGPI_HEIGHT_GAD;
#define MSG_PGPI_HEIGHT_GAD ((APTR) &_MSG_PGPI_HEIGHT_GAD)
extern const struct FC_Type _MSG_PGPI_DEPTH_GAD;
#define MSG_PGPI_DEPTH_GAD ((APTR) &_MSG_PGPI_DEPTH_GAD)
extern const struct FC_Type _MSG_PGPI_TYPE_GAD;
#define MSG_PGPI_TYPE_GAD ((APTR) &_MSG_PGPI_TYPE_GAD)
extern const struct FC_Type _MSG_PGPI_TYPE_L0_GAD;
#define MSG_PGPI_TYPE_L0_GAD ((APTR) &_MSG_PGPI_TYPE_L0_GAD)
extern const struct FC_Type _MSG_PGPI_TYPE_L1_GAD;
#define MSG_PGPI_TYPE_L1_GAD ((APTR) &_MSG_PGPI_TYPE_L1_GAD)
extern const struct FC_Type _MSG_PGPI_TYPE_L2_GAD;
#define MSG_PGPI_TYPE_L2_GAD ((APTR) &_MSG_PGPI_TYPE_L2_GAD)
extern const struct FC_Type _MSG_PGPI_SETPOINT_GAD;
#define MSG_PGPI_SETPOINT_GAD ((APTR) &_MSG_PGPI_SETPOINT_GAD)
extern const struct FC_Type _MSG_PGPI_PALETTE_GAD;
#define MSG_PGPI_PALETTE_GAD ((APTR) &_MSG_PGPI_PALETTE_GAD)
extern const struct FC_Type _MSG_TBP_PALETTE_GAD;
#define MSG_TBP_PALETTE_GAD ((APTR) &_MSG_TBP_PALETTE_GAD)
extern const struct FC_Type _MSG_Screen_WND;
#define MSG_Screen_WND ((APTR) &_MSG_Screen_WND)
extern const struct FC_Type _MSG_SCREEN_PAGES_L0_GAD;
#define MSG_SCREEN_PAGES_L0_GAD ((APTR) &_MSG_SCREEN_PAGES_L0_GAD)
extern const struct FC_Type _MSG_SCREEN_PAGES_L1_GAD;
#define MSG_SCREEN_PAGES_L1_GAD ((APTR) &_MSG_SCREEN_PAGES_L1_GAD)
extern const struct FC_Type _MSG_PGSCR_WIDTH_GAD;
#define MSG_PGSCR_WIDTH_GAD ((APTR) &_MSG_PGSCR_WIDTH_GAD)
extern const struct FC_Type _MSG_PGSCR_HEIGHT_GAD;
#define MSG_PGSCR_HEIGHT_GAD ((APTR) &_MSG_PGSCR_HEIGHT_GAD)
extern const struct FC_Type _MSG_PGSCR_DEPTH_GAD;
#define MSG_PGSCR_DEPTH_GAD ((APTR) &_MSG_PGSCR_DEPTH_GAD)
extern const struct FC_Type _MSG_PGSCR_TITLE_GAD;
#define MSG_PGSCR_TITLE_GAD ((APTR) &_MSG_PGSCR_TITLE_GAD)
extern const struct FC_Type _MSG_PGSCR_PUBNAME_GAD;
#define MSG_PGSCR_PUBNAME_GAD ((APTR) &_MSG_PGSCR_PUBNAME_GAD)
extern const struct FC_Type _MSG_PGSCR_USE_GAD;
#define MSG_PGSCR_USE_GAD ((APTR) &_MSG_PGSCR_USE_GAD)
extern const struct FC_Type _MSG_PGSCR_USE_L0_GAD;
#define MSG_PGSCR_USE_L0_GAD ((APTR) &_MSG_PGSCR_USE_L0_GAD)
extern const struct FC_Type _MSG_PGSCR_USE_L1_GAD;
#define MSG_PGSCR_USE_L1_GAD ((APTR) &_MSG_PGSCR_USE_L1_GAD)
extern const struct FC_Type _MSG_PGSCR_USE_L2_GAD;
#define MSG_PGSCR_USE_L2_GAD ((APTR) &_MSG_PGSCR_USE_L2_GAD)
extern const struct FC_Type _MSG_PGSCR_MAKEPUBLIC_GAD;
#define MSG_PGSCR_MAKEPUBLIC_GAD ((APTR) &_MSG_PGSCR_MAKEPUBLIC_GAD)
extern const struct FC_Type _MSG_PGSCR_MODEID_GAD;
#define MSG_PGSCR_MODEID_GAD ((APTR) &_MSG_PGSCR_MODEID_GAD)
extern const struct FC_Type _MSG_PGSCR_MODEID_GET_GAD;
#define MSG_PGSCR_MODEID_GET_GAD ((APTR) &_MSG_PGSCR_MODEID_GET_GAD)
extern const struct FC_Type _MSG_PGSCR_DEFAULTID_GAD;
#define MSG_PGSCR_DEFAULTID_GAD ((APTR) &_MSG_PGSCR_DEFAULTID_GAD)
extern const struct FC_Type _MSG_PGSCR_SHOWTITLE_GAD;
#define MSG_PGSCR_SHOWTITLE_GAD ((APTR) &_MSG_PGSCR_SHOWTITLE_GAD)
extern const struct FC_Type _MSG_PGSCR_BEHIND_GAD;
#define MSG_PGSCR_BEHIND_GAD ((APTR) &_MSG_PGSCR_BEHIND_GAD)
extern const struct FC_Type _MSG_PGSCR_QUIET_GAD;
#define MSG_PGSCR_QUIET_GAD ((APTR) &_MSG_PGSCR_QUIET_GAD)
extern const struct FC_Type _MSG_PGSCR_AUTOSCROLL_GAD;
#define MSG_PGSCR_AUTOSCROLL_GAD ((APTR) &_MSG_PGSCR_AUTOSCROLL_GAD)
extern const struct FC_Type _MSG_PGSCR_FULLPALETTE_GAD;
#define MSG_PGSCR_FULLPALETTE_GAD ((APTR) &_MSG_PGSCR_FULLPALETTE_GAD)
extern const struct FC_Type _MSG_PGSCR_DRAGGABLE_GAD;
#define MSG_PGSCR_DRAGGABLE_GAD ((APTR) &_MSG_PGSCR_DRAGGABLE_GAD)
extern const struct FC_Type _MSG_PGSCR_EXCLUSIVE_GAD;
#define MSG_PGSCR_EXCLUSIVE_GAD ((APTR) &_MSG_PGSCR_EXCLUSIVE_GAD)
extern const struct FC_Type _MSG_PGSCR_SHAREPENS_GAD;
#define MSG_PGSCR_SHAREPENS_GAD ((APTR) &_MSG_PGSCR_SHAREPENS_GAD)
extern const struct FC_Type _MSG_PGSCR_INTERLEAVED_GAD;
#define MSG_PGSCR_INTERLEAVED_GAD ((APTR) &_MSG_PGSCR_INTERLEAVED_GAD)
extern const struct FC_Type _MSG_PGSCR_LIKEWORKBENCH_GAD;
#define MSG_PGSCR_LIKEWORKBENCH_GAD ((APTR) &_MSG_PGSCR_LIKEWORKBENCH_GAD)
extern const struct FC_Type _MSG_PGSCR_MINIMIZEISG_GAD;
#define MSG_PGSCR_MINIMIZEISG_GAD ((APTR) &_MSG_PGSCR_MINIMIZEISG_GAD)
extern const struct FC_Type _MSG_EditString_WND;
#define MSG_EditString_WND ((APTR) &_MSG_EditString_WND)
extern const struct FC_Type _MSG_PGSTR_STRINGS_FORMAT_GAD;
#define MSG_PGSTR_STRINGS_FORMAT_GAD ((APTR) &_MSG_PGSTR_STRINGS_FORMAT_GAD)
extern const struct FC_Type _MSG_PGSTR_ADD_GAD;
#define MSG_PGSTR_ADD_GAD ((APTR) &_MSG_PGSTR_ADD_GAD)
extern const struct FC_Type _MSG_PGSTR_DELETE_GAD;
#define MSG_PGSTR_DELETE_GAD ((APTR) &_MSG_PGSTR_DELETE_GAD)
extern const struct FC_Type _MSG_PGSTR_EDIT_GAD;
#define MSG_PGSTR_EDIT_GAD ((APTR) &_MSG_PGSTR_EDIT_GAD)
extern const struct FC_Type _MSG_PGSTR_LABEL_GAD;
#define MSG_PGSTR_LABEL_GAD ((APTR) &_MSG_PGSTR_LABEL_GAD)
extern const struct FC_Type _MSG_PGSTR_STRING_GAD;
#define MSG_PGSTR_STRING_GAD ((APTR) &_MSG_PGSTR_STRING_GAD)
extern const struct FC_Type _MSG_EditVersion_WND;
#define MSG_EditVersion_WND ((APTR) &_MSG_EditVersion_WND)
extern const struct FC_Type _MSG_PGVER_PROGRAMNAME_GAD;
#define MSG_PGVER_PROGRAMNAME_GAD ((APTR) &_MSG_PGVER_PROGRAMNAME_GAD)
extern const struct FC_Type _MSG_PGVER_AUTHOR_GAD;
#define MSG_PGVER_AUTHOR_GAD ((APTR) &_MSG_PGVER_AUTHOR_GAD)
extern const struct FC_Type _MSG_PGVER_VERSION_GAD;
#define MSG_PGVER_VERSION_GAD ((APTR) &_MSG_PGVER_VERSION_GAD)
extern const struct FC_Type _MSG_PGVER_DATE_GAD;
#define MSG_PGVER_DATE_GAD ((APTR) &_MSG_PGVER_DATE_GAD)
extern const struct FC_Type _MSG_PGVER_REVISION_GAD;
#define MSG_PGVER_REVISION_GAD ((APTR) &_MSG_PGVER_REVISION_GAD)
extern const struct FC_Type _MSG_PG_TRLV_FLAGS_COLUMNS_GAD;
#define MSG_PG_TRLV_FLAGS_COLUMNS_GAD ((APTR) &_MSG_PG_TRLV_FLAGS_COLUMNS_GAD)
extern const struct FC_Type _MSG_PG_TRLV_FLAGS_FORMAT_GAD;
#define MSG_PG_TRLV_FLAGS_FORMAT_GAD ((APTR) &_MSG_PG_TRLV_FLAGS_FORMAT_GAD)
extern const struct FC_Type _MSG_PG_TRLV_FLAGS_DISABLED_GAD;
#define MSG_PG_TRLV_FLAGS_DISABLED_GAD ((APTR) &_MSG_PG_TRLV_FLAGS_DISABLED_GAD)
extern const struct FC_Type _MSG_PG_TRLV_FLAGS_MULTISELECT_GAD;
#define MSG_PG_TRLV_FLAGS_MULTISELECT_GAD ((APTR) &_MSG_PG_TRLV_FLAGS_MULTISELECT_GAD)
extern const struct FC_Type _MSG_PG_TRLV_FLAGS_BORDER_GAD;
#define MSG_PG_TRLV_FLAGS_BORDER_GAD ((APTR) &_MSG_PG_TRLV_FLAGS_BORDER_GAD)
extern const struct FC_Type _MSG_PG_TRLV_FLAGS_READONLY_GAD;
#define MSG_PG_TRLV_FLAGS_READONLY_GAD ((APTR) &_MSG_PG_TRLV_FLAGS_READONLY_GAD)
extern const struct FC_Type _MSG_PG_TRLV_FLAGS_SHOWTREELINES_GAD;
#define MSG_PG_TRLV_FLAGS_SHOWTREELINES_GAD ((APTR) &_MSG_PG_TRLV_FLAGS_SHOWTREELINES_GAD)
extern const struct FC_Type _MSG_PG_TRLV_FLAGS_SHOWSELECTED_GAD;
#define MSG_PG_TRLV_FLAGS_SHOWSELECTED_GAD ((APTR) &_MSG_PG_TRLV_FLAGS_SHOWSELECTED_GAD)
extern const struct FC_Type _MSG_PG_TRLV_FLAGS_TREE_GAD;
#define MSG_PG_TRLV_FLAGS_TREE_GAD ((APTR) &_MSG_PG_TRLV_FLAGS_TREE_GAD)
extern const struct FC_Type _MSG_Object_WND;
#define MSG_Object_WND ((APTR) &_MSG_Object_WND)
extern const struct FC_Type _MSG_EditPalette_WND;
#define MSG_EditPalette_WND ((APTR) &_MSG_EditPalette_WND)
extern const struct FC_Type _MSG_PAL_PALETTE_GAD;
#define MSG_PAL_PALETTE_GAD ((APTR) &_MSG_PAL_PALETTE_GAD)
extern const struct FC_Type _MSG_PAL_GREEN_GAD;
#define MSG_PAL_GREEN_GAD ((APTR) &_MSG_PAL_GREEN_GAD)
extern const struct FC_Type _MSG_PAL_GREEN_FORMAT_GAD;
#define MSG_PAL_GREEN_FORMAT_GAD ((APTR) &_MSG_PAL_GREEN_FORMAT_GAD)
extern const struct FC_Type _MSG_PAL_BLUE_GAD;
#define MSG_PAL_BLUE_GAD ((APTR) &_MSG_PAL_BLUE_GAD)
extern const struct FC_Type _MSG_PAL_BLUE_FORMAT_GAD;
#define MSG_PAL_BLUE_FORMAT_GAD ((APTR) &_MSG_PAL_BLUE_FORMAT_GAD)
extern const struct FC_Type _MSG_PAL_RED_GAD;
#define MSG_PAL_RED_GAD ((APTR) &_MSG_PAL_RED_GAD)
extern const struct FC_Type _MSG_PAL_RED_FORMAT_GAD;
#define MSG_PAL_RED_FORMAT_GAD ((APTR) &_MSG_PAL_RED_FORMAT_GAD)
extern const struct FC_Type _MSG_PAL_CANCEL_GAD;
#define MSG_PAL_CANCEL_GAD ((APTR) &_MSG_PAL_CANCEL_GAD)
extern const struct FC_Type _MSG_PAL_OK_GAD;
#define MSG_PAL_OK_GAD ((APTR) &_MSG_PAL_OK_GAD)
extern const struct FC_Type _MSG_PGWN_TABORDER_DOWN_GAD;
#define MSG_PGWN_TABORDER_DOWN_GAD ((APTR) &_MSG_PGWN_TABORDER_DOWN_GAD)
extern const struct FC_Type _MSG_PGWN_TABORDER_UP_GAD;
#define MSG_PGWN_TABORDER_UP_GAD ((APTR) &_MSG_PGWN_TABORDER_UP_GAD)
extern const struct FC_Type _MSG_PGWN_TABORDER_LIST_GAD;
#define MSG_PGWN_TABORDER_LIST_GAD ((APTR) &_MSG_PGWN_TABORDER_LIST_GAD)
extern const struct FC_Type _MSG_STATUS_CHANGED_GAD;
#define MSG_STATUS_CHANGED_GAD ((APTR) &_MSG_STATUS_CHANGED_GAD)
extern const struct FC_Type _MSG_STATUS_TEXT_GAD;
#define MSG_STATUS_TEXT_GAD ((APTR) &_MSG_STATUS_TEXT_GAD)
extern const struct FC_Type _MSG_CANTALLOCREQ;
#define MSG_CANTALLOCREQ ((APTR) &_MSG_CANTALLOCREQ)
extern const struct FC_Type _MSG_CANTALLOCOBJECT;
#define MSG_CANTALLOCOBJECT ((APTR) &_MSG_CANTALLOCOBJECT)
extern const struct FC_Type _MSG_CANTOPENTOOLBAR;
#define MSG_CANTOPENTOOLBAR ((APTR) &_MSG_CANTOPENTOOLBAR)
extern const struct FC_Type _MSG_CANTOPENOBJECTWINDOW;
#define MSG_CANTOPENOBJECTWINDOW ((APTR) &_MSG_CANTOPENOBJECTWINDOW)
extern const struct FC_Type _MSG_CANTOPENCLIPBOARD;
#define MSG_CANTOPENCLIPBOARD ((APTR) &_MSG_CANTOPENCLIPBOARD)
extern const struct FC_Type _MSG_GAD_BUTTON;
#define MSG_GAD_BUTTON ((APTR) &_MSG_GAD_BUTTON)
extern const struct FC_Type _MSG_GAD_CHECKBOX;
#define MSG_GAD_CHECKBOX ((APTR) &_MSG_GAD_CHECKBOX)
extern const struct FC_Type _MSG_GAD_COLORWHEEL;
#define MSG_GAD_COLORWHEEL ((APTR) &_MSG_GAD_COLORWHEEL)
extern const struct FC_Type _MSG_GAD_CYCLE;
#define MSG_GAD_CYCLE ((APTR) &_MSG_GAD_CYCLE)
extern const struct FC_Type _MSG_GAD_DATATYPE;
#define MSG_GAD_DATATYPE ((APTR) &_MSG_GAD_DATATYPE)
extern const struct FC_Type _MSG_GAD_GRADIENTSLIDER;
#define MSG_GAD_GRADIENTSLIDER ((APTR) &_MSG_GAD_GRADIENTSLIDER)
extern const struct FC_Type _MSG_GAD_INTEGER;
#define MSG_GAD_INTEGER ((APTR) &_MSG_GAD_INTEGER)
extern const struct FC_Type _MSG_GAD_LISTVIEW;
#define MSG_GAD_LISTVIEW ((APTR) &_MSG_GAD_LISTVIEW)
extern const struct FC_Type _MSG_GAD_MX;
#define MSG_GAD_MX ((APTR) &_MSG_GAD_MX)
extern const struct FC_Type _MSG_GAD_NUMBER;
#define MSG_GAD_NUMBER ((APTR) &_MSG_GAD_NUMBER)
extern const struct FC_Type _MSG_GAD_PAGE;
#define MSG_GAD_PAGE ((APTR) &_MSG_GAD_PAGE)
extern const struct FC_Type _MSG_GAD_PALETTE;
#define MSG_GAD_PALETTE ((APTR) &_MSG_GAD_PALETTE)
extern const struct FC_Type _MSG_GAD_POPUPMENU;
#define MSG_GAD_POPUPMENU ((APTR) &_MSG_GAD_POPUPMENU)
extern const struct FC_Type _MSG_GAD_PROGRESS;
#define MSG_GAD_PROGRESS ((APTR) &_MSG_GAD_PROGRESS)
extern const struct FC_Type _MSG_GAD_SCROLLER;
#define MSG_GAD_SCROLLER ((APTR) &_MSG_GAD_SCROLLER)
extern const struct FC_Type _MSG_GAD_SLIDER;
#define MSG_GAD_SLIDER ((APTR) &_MSG_GAD_SLIDER)
extern const struct FC_Type _MSG_GAD_STRING;
#define MSG_GAD_STRING ((APTR) &_MSG_GAD_STRING)
extern const struct FC_Type _MSG_GAD_TAPEDECK;
#define MSG_GAD_TAPEDECK ((APTR) &_MSG_GAD_TAPEDECK)
extern const struct FC_Type _MSG_GAD_TEXT;
#define MSG_GAD_TEXT ((APTR) &_MSG_GAD_TEXT)
extern const struct FC_Type _MSG_GAD_TEXTFIELD;
#define MSG_GAD_TEXTFIELD ((APTR) &_MSG_GAD_TEXTFIELD)
extern const struct FC_Type _MSG_GAD_TREEVIEW;
#define MSG_GAD_TREEVIEW ((APTR) &_MSG_GAD_TREEVIEW)
extern const struct FC_Type _MSG_NEW;
#define MSG_NEW ((APTR) &_MSG_NEW)
extern const struct FC_Type _MSG_LOADING;
#define MSG_LOADING ((APTR) &_MSG_LOADING)
extern const struct FC_Type _MSG_SAVING;
#define MSG_SAVING ((APTR) &_MSG_SAVING)
extern const struct FC_Type _MSG_GENERATING;
#define MSG_GENERATING ((APTR) &_MSG_GENERATING)
extern const struct FC_Type _MSG_ABOUT;
#define MSG_ABOUT ((APTR) &_MSG_ABOUT)
extern const struct FC_Type _MSG_ERROPENLIB_GRADIENTSLIDER;
#define MSG_ERROPENLIB_GRADIENTSLIDER ((APTR) &_MSG_ERROPENLIB_GRADIENTSLIDER)
extern const struct FC_Type _MSG_NEWTITLE;
#define MSG_NEWTITLE ((APTR) &_MSG_NEWTITLE)
extern const struct FC_Type _MSG_NEWITEM;
#define MSG_NEWITEM ((APTR) &_MSG_NEWITEM)
extern const struct FC_Type _MSG_NEWSUB;
#define MSG_NEWSUB ((APTR) &_MSG_NEWSUB)
extern const struct FC_Type _MSG_CHANGEME;
#define MSG_CHANGEME ((APTR) &_MSG_CHANGEME)
extern const struct FC_Type _MSG_EDITSTR_STRING;
#define MSG_EDITSTR_STRING ((APTR) &_MSG_EDITSTR_STRING)
extern const struct FC_Type _MSG_UNNAMED;
#define MSG_UNNAMED ((APTR) &_MSG_UNNAMED)
extern const struct FC_Type _MSG_EMPTY;
#define MSG_EMPTY ((APTR) &_MSG_EMPTY)
extern const struct FC_Type _MSG_UNTITLED;
#define MSG_UNTITLED ((APTR) &_MSG_UNTITLED)
extern const struct FC_Type _MSG_UNKNOWN;
#define MSG_UNKNOWN ((APTR) &_MSG_UNKNOWN)
extern const struct FC_Type _MSG_OK;
#define MSG_OK ((APTR) &_MSG_OK)
extern const struct FC_Type _MSG_ERROR;
#define MSG_ERROR ((APTR) &_MSG_ERROR)
extern const struct FC_Type _MSG_YOUNEEDNEWERVERSION;
#define MSG_YOUNEEDNEWERVERSION ((APTR) &_MSG_YOUNEEDNEWERVERSION)
extern const struct FC_Type _MSG_ERRCREATEPROJECTPORT;
#define MSG_ERRCREATEPROJECTPORT ((APTR) &_MSG_ERRCREATEPROJECTPORT)
extern const struct FC_Type _MSG_ERRCREATEPOINTER;
#define MSG_ERRCREATEPOINTER ((APTR) &_MSG_ERRCREATEPOINTER)
extern const struct FC_Type _MSG_ERRCREATEIMAGE;
#define MSG_ERRCREATEIMAGE ((APTR) &_MSG_ERRCREATEIMAGE)
extern const struct FC_Type _MSG_PGDT_DTOBJ;
#define MSG_PGDT_DTOBJ ((APTR) &_MSG_PGDT_DTOBJ)
extern const struct FC_Type _MSG_ERROPENLIB_COLORWHEEL;
#define MSG_ERROPENLIB_COLORWHEEL ((APTR) &_MSG_ERROPENLIB_COLORWHEEL)
extern const struct FC_Type _MSG_ALIGNLEFT;
#define MSG_ALIGNLEFT ((APTR) &_MSG_ALIGNLEFT)
extern const struct FC_Type _MSG_ALIGNHCENTER;
#define MSG_ALIGNHCENTER ((APTR) &_MSG_ALIGNHCENTER)
extern const struct FC_Type _MSG_ALIGNRIGHT;
#define MSG_ALIGNRIGHT ((APTR) &_MSG_ALIGNRIGHT)
extern const struct FC_Type _MSG_ALIGNTOP;
#define MSG_ALIGNTOP ((APTR) &_MSG_ALIGNTOP)
extern const struct FC_Type _MSG_ALIGNVCENTER;
#define MSG_ALIGNVCENTER ((APTR) &_MSG_ALIGNVCENTER)
extern const struct FC_Type _MSG_ALIGNBOTTOM;
#define MSG_ALIGNBOTTOM ((APTR) &_MSG_ALIGNBOTTOM)
extern const struct FC_Type _MSG_SPREADHORIZ;
#define MSG_SPREADHORIZ ((APTR) &_MSG_SPREADHORIZ)
extern const struct FC_Type _MSG_SPREADVERT;
#define MSG_SPREADVERT ((APTR) &_MSG_SPREADVERT)
extern const struct FC_Type _MSG_FRAMEOBJECT;
#define MSG_FRAMEOBJECT ((APTR) &_MSG_FRAMEOBJECT)
extern const struct FC_Type _MSG_GADGETOBJECT;
#define MSG_GADGETOBJECT ((APTR) &_MSG_GADGETOBJECT)
extern const struct FC_Type _MSG_WINDOWOBJECT;
#define MSG_WINDOWOBJECT ((APTR) &_MSG_WINDOWOBJECT)
extern const struct FC_Type _MSG_IMAGEOBJECT;
#define MSG_IMAGEOBJECT ((APTR) &_MSG_IMAGEOBJECT)
extern const struct FC_Type _MSG_STRINGOBJECT;
#define MSG_STRINGOBJECT ((APTR) &_MSG_STRINGOBJECT)
extern const struct FC_Type _MSG_NOOBJECT;
#define MSG_NOOBJECT ((APTR) &_MSG_NOOBJECT)
extern const struct FC_Type _MSG_MENUOBJECT;
#define MSG_MENUOBJECT ((APTR) &_MSG_MENUOBJECT)
extern const struct FC_Type _MSG_CONFIRMATION;
#define MSG_CONFIRMATION ((APTR) &_MSG_CONFIRMATION)
extern const struct FC_Type _MSG_REPLACEFILE;
#define MSG_REPLACEFILE ((APTR) &_MSG_REPLACEFILE)
extern const struct FC_Type _MSG_YESNO;
#define MSG_YESNO ((APTR) &_MSG_YESNO)
extern const struct FC_Type _MSG_CANTOPENSTATUSWINDOW;
#define MSG_CANTOPENSTATUSWINDOW ((APTR) &_MSG_CANTOPENSTATUSWINDOW)
extern const struct FC_Type _MSG_CANTOPENPROPERTIESWINDOW;
#define MSG_CANTOPENPROPERTIESWINDOW ((APTR) &_MSG_CANTOPENPROPERTIESWINDOW)
extern const struct FC_Type _MSG_STATUS_RESLOADED;
#define MSG_STATUS_RESLOADED ((APTR) &_MSG_STATUS_RESLOADED)
extern const struct FC_Type _MSG_STATUS_RESSAVED;
#define MSG_STATUS_RESSAVED ((APTR) &_MSG_STATUS_RESSAVED)
extern const struct FC_Type _MSG_STATUS_MOVINGOBJECT;
#define MSG_STATUS_MOVINGOBJECT ((APTR) &_MSG_STATUS_MOVINGOBJECT)
extern const struct FC_Type _MSG_STATUS_RESIZINGOBJECT;
#define MSG_STATUS_RESIZINGOBJECT ((APTR) &_MSG_STATUS_RESIZINGOBJECT)
extern const struct FC_Type _MSG_STATUS_RESGENERATED;
#define MSG_STATUS_RESGENERATED ((APTR) &_MSG_STATUS_RESGENERATED)
extern const struct FC_Type _MSG_STATUS_CREATINGOBJECT;
#define MSG_STATUS_CREATINGOBJECT ((APTR) &_MSG_STATUS_CREATINGOBJECT)
extern const struct FC_Type _MSG_STATUS_SELECTINGOBJECTS;
#define MSG_STATUS_SELECTINGOBJECTS ((APTR) &_MSG_STATUS_SELECTINGOBJECTS)
extern const struct FC_Type _MSG_ERROPENLIB_PAGE;
#define MSG_ERROPENLIB_PAGE ((APTR) &_MSG_ERROPENLIB_PAGE)
extern const struct FC_Type _MSG_ERROPENLIB_PROGRESS;
#define MSG_ERROPENLIB_PROGRESS ((APTR) &_MSG_ERROPENLIB_PROGRESS)
extern const struct FC_Type _MSG_ERROPENLIB_TEXTFIELD;
#define MSG_ERROPENLIB_TEXTFIELD ((APTR) &_MSG_ERROPENLIB_TEXTFIELD)
extern const struct FC_Type _MSG_ERROPENLIB_TREEVIEW;
#define MSG_ERROPENLIB_TREEVIEW ((APTR) &_MSG_ERROPENLIB_TREEVIEW)
extern const struct FC_Type _MSG_ERROPENLIB_SMARTBITMAP;
#define MSG_ERROPENLIB_SMARTBITMAP ((APTR) &_MSG_ERROPENLIB_SMARTBITMAP)
extern const struct FC_Type _MSG_ERR_OPENSCREEN;
#define MSG_ERR_OPENSCREEN ((APTR) &_MSG_ERR_OPENSCREEN)
extern const struct FC_Type _MSG_ERR_VISUALINFO;
#define MSG_ERR_VISUALINFO ((APTR) &_MSG_ERR_VISUALINFO)
extern const struct FC_Type _MSG_ERR_SCRDRAWINFO;
#define MSG_ERR_SCRDRAWINFO ((APTR) &_MSG_ERR_SCRDRAWINFO)
extern const struct FC_Type _MSG_ERR_UNKNOWN;
#define MSG_ERR_UNKNOWN ((APTR) &_MSG_ERR_UNKNOWN)
extern const struct FC_Type _MSG_ERROPENLIB_TAPEDECK;
#define MSG_ERROPENLIB_TAPEDECK ((APTR) &_MSG_ERROPENLIB_TAPEDECK)
extern const struct FC_Type _MSG_CANTCREATEPOPUPMENUS;
#define MSG_CANTCREATEPOPUPMENUS ((APTR) &_MSG_CANTCREATEPOPUPMENUS)
extern const struct FC_Type _MSG_ERROPENLIB_POPUPMENU;
#define MSG_ERROPENLIB_POPUPMENU ((APTR) &_MSG_ERROPENLIB_POPUPMENU)
extern const struct FC_Type _MSG_CANTCREATEPOPUPMENUCLASS;
#define MSG_CANTCREATEPOPUPMENUCLASS ((APTR) &_MSG_CANTCREATEPOPUPMENUCLASS)
extern const struct FC_Type _MSG_CANTCREATEDRAWCLASS;
#define MSG_CANTCREATEDRAWCLASS ((APTR) &_MSG_CANTCREATEDRAWCLASS)
extern const struct FC_Type _MSG_ABOUTUNREG;
#define MSG_ABOUTUNREG ((APTR) &_MSG_ABOUTUNREG)
extern const struct FC_Type _MSG_SELECTPROJECTFILE;
#define MSG_SELECTPROJECTFILE ((APTR) &_MSG_SELECTPROJECTFILE)
extern const struct FC_Type _MSG_SAVEPROJECTAS;
#define MSG_SAVEPROJECTAS ((APTR) &_MSG_SAVEPROJECTAS)
extern const struct FC_Type _MSG_ENTERBASENAME;
#define MSG_ENTERBASENAME ((APTR) &_MSG_ENTERBASENAME)
extern const struct FC_Type _MSG_NOTSAVED;
#define MSG_NOTSAVED ((APTR) &_MSG_NOTSAVED)


#endif /* gadtools_cat_H */
