#include<proto/utility.h>
#include<exec/types.h>
#include<gadtoolsbox/gadtoolsbox.h>

#define TOOL_HORIZ 0
#define TOOL_VERT 1

#define TYPE_INTUIMESSAGE 0
#define TYPE_VERTSCROLL 1
#define TYPE_HORIZSCROLL 2
#define TYPE_APPMESSAGE 3
#define TYPE_INIT 4
#define TYPE_DELETE 5

#define WIND_Dummy (TAG_USER)
#define WIND_VertScroll (WIND_Dummy+0)
#define WIND_VertTop (WIND_Dummy+1)
#define WIND_VertTotal (WIND_Dummy+2)
#define WIND_VertVisible (WIND_Dummy+3)
#define WIND_HorizScroll (WIND_Dummy+4)
#define WIND_HorizTop (WIND_Dummy+5)
#define WIND_HorizTotal (WIND_Dummy+6)
#define WIND_HorizVisible (WIND_Dummy+7)
#define WIND_Left (WIND_Dummy+8)
#define WIND_RelRight (WIND_Dummy+9)
#define WIND_CenterX (WIND_Dummy+10)
#define WIND_Top (WIND_Dummy+11)
#define WIND_RelBottom (WIND_Dummy+12)
#define WIND_CenterY (WIND_Dummy+13)
#define WIND_Width (WIND_Dummy+14)
#define WIND_InnerWidth (WIND_Dummy+15)
#define WIND_RelWidth (WIND_Dummy+16)
#define WIND_Height (WIND_Dummy+17)
#define WIND_InnerHeight (WIND_Dummy+18)
#define WIND_RelHeight (WIND_Dummy+19)
#define WIND_Screen (WIND_Dummy+20)
#define WIND_PubScreen (WIND_Dummy+21)
#define WIND_PubScreenName (WIND_Dummy+22)
#define WIND_IDCMP (WIND_Dummy+23)
#define WIND_MessagePort (WIND_Dummy+24)
#define WIND_AppMessagePort (WIND_Dummy+25)
#define WIND_AppID (WIND_Dummy+26)
#define WIND_ToolDragBar (WIND_Dummy+27)
#define WIND_MenuStrip (WIND_Dummy+28)
#define WIND_Gadgets (WIND_Dummy+29)
#define WIND_LockWindow (WIND_Dummy+30)
#define WIND_Handler (WIND_Dummy+31)
#define WIND_ScreenObject (WIND_Dummy+32)

#define WIND_Window (WIND_Dummy+100)
#define WIND_RastPort (WIND_Dummy+101)
#define WIND_BorderLeft (WIND_Dummy+102)
#define WIND_BorderTop (WIND_Dummy+103)
#define WIND_BorderRight (WIND_Dummy+104)
#define WIND_BorderBottom (WIND_Dummy+105)
#define WIND_SigBit (WIND_Dummy+106)

#define WIND_Title               WA_Title
#define WIND_SuperBitMap         WA_SuperBitMap
#define WIND_MinWidth            WA_MinWidth
#define WIND_MinHeight           WA_MinHeight
#define WIND_MaxWidth            WA_MaxWidth
#define WIND_MaxHeight           WA_MaxHeight
#define WIND_SizeGadget          WA_SizeGadget
#define WIND_DragBar             WA_DragBar
#define WIND_DepthGadget         WA_DepthGadget
#define WIND_CloseGadget         WA_CloseGadget
#define WIND_Backdrop            WA_Backdrop
#define WIND_ReportMouse         WA_ReportMouse
#define WIND_NoCareRefresh       WA_NoCareRefresh
#define WIND_Borderless          WA_Borderless
#define WIND_Activate            WA_Activate
#define WIND_RMBTrap             WA_RMBTrap
#define WIND_SimpleRefresh       WA_SimpleRefresh
#define WIND_SmartRefresh        WA_SmartRefresh
#define WIND_SizeBRight          WA_SizeBRight
#define WIND_SizeBBottom         WA_SizeBBottom
#define WIND_GimmeZeroZero       WA_GimmeZeroZero
#define WIND_NewLookMenus        WA_NewLookMenus
#define WIND_ScreenTitle         WA_ScreenTitle
#define WIND_AutoAdjust          WA_AutoAdjust
#define WIND_PubScreenFallBack   WA_PubScreenFallBack
#define WIND_Zoom                WA_Zoom
#define WIND_MouseQueue          WA_MouseQueue
#define WIND_RptQueue            WA_RptQueue
#define WIND_BackFill            WA_BackFill
#define WIND_MenuHelp            WA_MenuHelp
#define WIND_NotifyDepth         WA_NotifyDepth
#define WIND_Checkmark           WA_Checkmark
#define WIND_AmigaKey            WA_AmigaKey
#define WIND_Pointer             WA_Pointer
#define WIND_BusyPointer         WA_BusyPointer
#define WIND_PointerDelay        WA_PointerDelay
#define WIND_HelpGroup           WA_HelpGroup
#define WIND_HelpGroupWindow     WA_HelpGroupWindow
#define WIND_TabletMessages      WA_TabletMessages
#define WIND_SizeBRight          WA_SizeBRight
#define WIND_SizeBBottom         WA_SizeBBottom
#define WIND_ID                  GA_ID
#define WIND_UserData            GA_UserData
